
/* =========================================================
   HONEYMOON — Catalogue (front-end only)
   - Accès agence : réservé au vrai compte admin (Firebase Auth,
     email + mot de passe) — plus de mot de passe partagé en clair.
   Les données (texte, photos, vidéos, PDF contrat) sont
   sauvegardées dans le localStorage de CE navigateur
   uniquement. Le navigateur limite en général ce stockage
   à quelques Mo au total : des vidéos, même peu nombreuses,
   peuvent vite atteindre cette limite. Pour un vrai stockage
   illimité et partagé entre plusieurs appareils/agences, il
   faut un vrai backend (serveur + base de données / cloud
   storage) — dis-le moi si tu veux qu'on regarde cette étape.
   ========================================================= */

const CONTACT_EMAIL = 'honeymoon-official@outlook.com';

/* ---------------- indicateur de chargement global pour <img>/<video> -----------------
   Le site injecte énormément de contenu (photos, vidéos) via innerHTML un peu partout.
   Plutôt que de modifier chaque endroit un par un, on observe tout le document et on
   affiche un effet de chargement (shimmer) tant que le média n'est pas prêt, puis un
   fondu à l'apparition. Ça évite l'impression de "bug" quand une photo/vidéo met du
   temps à charger (réseau lent, Firebase Storage, etc.) — c'est maintenant visible
   comme un chargement normal, pas comme un blocage. */
function hmInitMediaLoading(el){
  if(el.dataset.hmMediaInit) return;
  el.dataset.hmMediaInit = '1';
  const isVideo = el.tagName === 'VIDEO';
  const ready = isVideo ? (el.readyState >= 2) : (el.complete && el.naturalWidth > 0);
  if(ready){ el.setAttribute('data-hm-loaded', ''); return; }
  el.setAttribute('data-hm-loading', '');
  const onReady = () => { el.removeAttribute('data-hm-loading'); el.setAttribute('data-hm-loaded', ''); };
  el.addEventListener(isVideo ? 'loadeddata' : 'load', onReady, { once:true });
  el.addEventListener('error', onReady, { once:true });
}
function hmScanMedia(root){
  (root || document).querySelectorAll('img:not([data-hm-media-init]), video:not([data-hm-media-init])').forEach(hmInitMediaLoading);
}
hmScanMedia();
if(window.MutationObserver){
  let hmScanScheduled = false;
  const hmObserver = new MutationObserver(() => {
    if(hmScanScheduled) return;
    hmScanScheduled = true;
    requestAnimationFrame(() => { hmScanScheduled = false; hmScanMedia(); });
  });
  hmObserver.observe(document.body, { childList:true, subtree:true });
}

/* ===== À REMPLIR : coordonnées bancaires affichées au client après sa demande de déblocage
   (en attendant l'ouverture d'un compte CCBill). Modifie les valeurs ci-dessous. ===== */
const PAYMENT_INSTRUCTIONS = {
  iban: 'FR76 XXXX XXXX XXXX XXXX XXXX XXX',
  bic: 'XXXXXXXX',
  holder: 'Prince Mickael',
  note: 'Merci d\'indiquer la référence de commande en libellé du virement.'
};
const DEFAULT_SPLIT_CREATOR_PERCENT = 60;

/* ===== À REMPLIR : notifications automatiques (email + WhatsApp) quand
   un client demande à débloquer un contenu payant.
   ------------------------------------------------------------------
   EMAIL (EmailJS — gratuit jusqu'à 200 emails/mois, sans backend) :
   1. Crée un compte sur https://www.emailjs.com
   2. Connecte ta boîte mail (Gmail/Outlook) comme "Email Service" → note son ID
   3. Crée un template avec les variables : {{to_email}} {{buyer_name}}
      {{buyer_contact}} {{creator_name}} {{item_desc}} {{price}} {{ref}}
   4. Remplace les 3 valeurs ci-dessous par les tiennes (Account → API Keys
      pour la clé publique)
   ------------------------------------------------------------------
   WHATSAPP : remplace par ton numéro Honeymoon au format international
   sans + ni espace (ex. 33612345678 pour la France). ===== */
const EMAILJS_PUBLIC_KEY = 'TON_EMAILJS_PUBLIC_KEY';
const EMAILJS_SERVICE_ID = 'TON_EMAILJS_SERVICE_ID';
const EMAILJS_TEMPLATE_ID = 'TON_EMAILJS_TEMPLATE_ID';
const ADMIN_NOTIFY_EMAIL = 'honeymoon-official@outlook.com';
const ADMIN_WHATSAPP_NUMBER = '33XXXXXXXXX';

async function sendUnlockNotifications(o){
  // Email — nécessite EmailJS configuré ci-dessus. Échoue silencieusement
  // (avec log console) si non configuré, sans bloquer la commande.
  try{
    if(typeof emailjs !== 'undefined' && EMAILJS_PUBLIC_KEY !== 'TON_EMAILJS_PUBLIC_KEY'){
      const payload = {
        buyer_name: o.buyerName, buyer_contact: o.buyerContact, creator_name: o.creatorName,
        item_desc: o.itemDesc || '', price: o.price, ref: o.ref
      };
      // Email au client (instructions de paiement)
      await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, Object.assign({}, payload, {
        to_email: o.buyerContact, subject: `Honeymoon — Instructions de paiement (réf. ${o.ref})`
      }));
      // Email à Honeymoon (notification de commande)
      await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, Object.assign({}, payload, {
        to_email: ADMIN_NOTIFY_EMAIL, subject: `Honeymoon — Nouvelle demande de déblocage (réf. ${o.ref})`
      }));
    }
  }catch(e){ console.error('emailjs notification error', e); }
}
function buildAdminWhatsappLink(o){
  const msg = encodeURIComponent(
    `Honeymoon — Nouvelle demande de déblocage\nRéf: ${o.ref}\nCréatrice: ${o.creatorName}\nClient: ${o.buyerName} (${o.buyerContact})\nContenu: ${o.itemDesc || ''}\nPrix: ${o.price}€`
  );
  return `https://wa.me/${ADMIN_WHATSAPP_NUMBER}?text=${msg}`;
}
const STORAGE_KEY = 'hm_catalogue_v3';
/* ===== Accès agence par code : NE contient AUCUN mot de passe en clair.
   Le code tapé est utilisé comme mot de passe d'un compte Firebase technique
   dédié (email fixe ci-dessous). Pour créer/changer le code :
   Firebase Console → Authentication → Users → Add user, avec CET email exact
   et le code de ton choix comme mot de passe. Change-le à tout moment depuis
   Firebase sans jamais toucher au code du site. ===== */
const AGENCY_ACCESS_EMAIL = 'princeprojet@outlook.com';
/* ===== Code de test LOCAL UNIQUEMENT (pour tes essais avant hébergement).
   Ne fonctionne JAMAIS une fois le site réellement hébergé (vercel.app) —
   uniquement quand le fichier est ouvert directement (content://, file://).
   Change-le si tu veux, ou laisse tel quel : sans impact une fois en ligne. ===== */
const LOCAL_TEST_CODE = '1988';
const LOCAL_TEST_EMAIL = 'nakupendayangu@outlook.com';
/* Mot de passe RÉEL du compte membre de test (à créer une fois dans Firebase Auth, projet membres,
   avec exactement ce mot de passe — 6 caractères minimum imposés par Firebase).
   En local, taper "1988" comme mot de passe le remplace automatiquement par celui-ci. */
const LOCAL_TEST_MEMBER_REAL_PASSWORD = '1988TEST';
function isLocalTestEnvironment(){
  const proto = window.location.protocol;
  return proto !== 'https:' && proto !== 'http:';
}
const SLOT_COUNT = 150; // capacité totale du roster (nombre d'emplacements possibles) — la vitrine affiche 6 vignettes par page (voir VITRINE_PAGE_SIZE), avec navigation ‹ › entre les pages.

// ===== Ancien système (codes fixes par créatrice, comparés côté client) — retiré :
// ne passait pas à l'échelle au-delà d'une poignée de créatrices, et n'offrait
// aucune vraie sécurité côté serveur. Remplacé par un vrai compte Firebase Auth
// par créatrice (email + mot de passe), identifié via le champ "ownerEmail" sur
// son propre document profils/{id} — voir le formulaire d'édition (admin) et
// firestore.rules. Ajouter une nouvelle créatrice ne demande plus AUCUNE
// modification de code, quel que soit leur nombre : juste un compte Firebase
// Auth + le champ ownerEmail rempli dans son profil.

// Connexion à Firebase — utilisée UNIQUEMENT pour le login admin à cette étape.
// Les profils, photos, vidéos restent stockés comme avant (aucun changement).
const firebaseConfig = {
  apiKey: "AIzaSyDjeKf3_JL4FxxZQq_d6gdXdmc2Z5RxbaY",
  authDomain: "honeymoonproject2026.firebaseapp.com",
  projectId: "honeymoonproject2026",
  storageBucket: "honeymoonproject2026.firebasestorage.app",
  messagingSenderId: "529825855432",
  appId: "1:529825855432:web:20f97cb88e0ce2d35cf2fd"
};
let auth, db, storage;
let memberAuth, memberDb, memberStorage; // instances Firebase SÉPARÉES pour les comptes membres (n'affecte jamais isAdmin()/auth.currentUser)
try{
  firebase.initializeApp(firebaseConfig);
  auth = firebase.auth();
  db = firebase.firestore();
  storage = firebase.storage();
  const memberApp = firebase.initializeApp(firebaseConfig, 'memberApp');
  memberAuth = memberApp.auth();
  memberDb = memberApp.firestore();
  memberStorage = memberApp.storage();
  // La restauration de session est asynchrone : sans cet écouteur, le badge pseudo
  // (haut de page) et le menu "Devenir membre" ne se mettent jamais à jour tout
  // seuls après un rechargement de page.
  memberAuth.onAuthStateChanged(() => { try{ refreshMemberBadgeFromSession(); }catch(e){} });
}catch(e){
  console.error('Firebase init failed — le site continue de fonctionner sans synchronisation.', e);
}

const SUPPORTED_LANGS = ['fr','en','es','it','pt','sw','zu','st','ln','kg'];
function detectInitialLang(){
  // L'anglais est la langue par défaut du site : on ne devine plus la langue
  // depuis celle du téléphone/navigateur (un visiteur avec un téléphone en
  // français verra quand même l'anglais, comme prévu). Seul un choix déjà
  // fait explicitement par le visiteur (mémorisé) l'emporte sur l'anglais.
  try{
    const saved = localStorage.getItem('hm_lang');
    if(saved && SUPPORTED_LANGS.includes(saved)) return saved;
  }catch(e){}
  return 'en';
}
let LANG = detectInitialLang();

const I18N = {
  fr: {
    gateSub: 'Accès privé',
    gateEnter: 'Entrer',
    gateNoteB: 'Note technique :',
    gateNote: "ce code d'accès est une simple barrière côté navigateur, pas une vraie authentification.",
    gateErr: 'Code incorrect.',
    gatePassPh: "Code d'accès",
    creatorPassPh: "Mot de passe",
    creatorEmailPh: "Email",
    creatorEmailLabel: "Email de connexion (créatrice)",
    creatorEmailNote: "La créatrice crée elle-même son compte (lien \"Créer mon compte créatrice\" sur l'écran de connexion) — colle ici l'email qu'elle a choisi pour activer son profil. Fonctionne pour un nombre illimité de créatrices, sans jamais toucher au code.",
    creatorSignupLink: "Pas encore de compte ? Créer mon compte créatrice",
    creatorSignupSub: "Créer mon compte créatrice",
    creatorSignupNote: "Crée ton compte toi-même. Ton profil sera activé par l'équipe Honeymoon une fois ta candidature validée.",
    creatorSuSubmit: "Créer mon compte",
    creatorLoginLink: "← Retour à la connexion",
    creatorSignupSuccessToast: "Compte créé ! L'équipe va maintenant activer ton profil.",
    creatorNotActivatedErr: "Compte trouvé, mais aucun profil ne t'est encore rattaché. Contacte l'équipe Honeymoon.",
    noPhotoYet: "Aucune photo",
    tipMenuContentRequired: "Ajoute un contenu (photo, vidéo ou audio) avant d'enregistrer cette ligne.",
    mockPurchaseNotice: "🔧 Achat fictif — le vrai système de paiement arrive bientôt. Aucun montant n'a été prélevé.",
    visitorNeedsAccountPurchase: "Inscris-toi gratuitement pour acheter du contenu — un compte est nécessaire pour le stocker dans ta galerie personnelle.",
    memberLoggedInToast: "Connexion réussie !",
    memberBioEditBtn: "Modifier",
    memberBioCancelBtn: "Annuler",
    memberBioDeleteBtn: "Supprimer",
    memberBioEmpty: "Aucune biographie pour l'instant. Clique sur modifier pour en écrire une.",
    myFamilyComments: "Commentaires",
    tipMenuEarnNote: "Tu recevras environ {amount}€ (60%) sur ce prix.",
    tipMenuContentLabel: "Contenu à vendre",
    tipMenuContentNote: "Importe ou prends directement la photo/vidéo/audio que tu vas vendre pour ce thème.",
    tipMenuOrderBtn: "Commander",
    tipMenuOrderPrefill: "Bonjour, je souhaite commander : {theme} ({price}€)",
    tipOrderCardLabel: "Commande Tip Menu",
    tipOrderDeliverBtn: "Livrer / Réglé",
    ordersCustomTabLabel: "Commandes perso",
    ordersTipTabLabel: "Commandes Tip Menu",
    ordersCustomTabNote: "Toutes les demandes personnalisées reçues, avec le nom du membre et sa demande. Livre le contenu ou lance une discussion pour préciser les détails.",
    ordersTipTabNote: "Toutes les commandes passées depuis ton Tip Menu, avec le nom du membre. Le contenu existe déjà : clique sur Livrer / Réglé pour le débloquer, ou discute du délai de livraison.",
    ordersCustomEmpty: "Aucune commande personnalisée en attente.",
    ordersTipEmpty: "Aucune commande Tip Menu en attente.",
    ordersDiscussBtn: "💬 Discuter",
    tipMenuCurrencyCompareLink: "Comparer avec ma devise (Google)",
    chatModBtnLabel: "Conseils & règles",
    chatModTip1: "Sois respectueux(se) et bienveillant(e) : un bon échange commence toujours par de la politesse.",
    chatModTip2: "N'hésite pas à poser des questions ouvertes pour que la conversation reste fluide et agréable pour les deux.",
    customOrderTypeChooseLabel: "Choisis un type de contenu",
    customOrderTypeChooseNote: "Il y a 3 choix possibles : photo, vidéo ou audio. Sélectionne celui qui correspond à ce que tu vas livrer.",
    customOrderHelp1: "Cette commande est une demande sur-mesure : décris précisément ce que tu veux (durée, tenue, ambiance).",
    customOrderHelp2: "Reste respectueux(se) dans ta demande — pas de nudité, pas de contenu explicite ou illégal.",
    customOrderHelp3: "Le prix n'est pas négociable directement avec toi : c'est la créatrice qui fixe le prix (dans les limites de la plateforme) au moment de la livraison.",
    customOrderHelp4: "Une fois livrée, ta commande apparaît dans 'Mes achats' — tu peux la revoir à tout moment.",
    tipMenuHowTitle: "Comment ça marche ?",
    tipMenuHowP1: "Le Tip Menu, c'est ton menu de contenus déjà prêts : tu fixes un thème, un prix (dans la limite fixée par la plateforme) et tu importes directement la photo, vidéo ou audio à vendre.",
    tipMenuHowP2: "Il n'y a aucune négociation sur ces articles : le prix est déjà fixé avec la description. Le membre clique juste sur 'Commander' pour passer commande.",
    tipMenuHowP3: "Un membre peut aussi te demander une commande 100% personnalisée directement depuis le chat (bouton caddie) — c'est toi qui livres le contenu et fixes le prix à ce moment-là.",
    tipMenuHowMemberP1: "Le Tip Menu montre les contenus déjà prêts que la créatrice propose, avec leur prix.",
    tipMenuHowMemberP2: "Pas de négociation : le prix est déjà fixé avec la description. Clique sur 'Commander' pour passer ta commande directement.",
    tipMenuHowMemberP3: "Tu peux aussi lui demander quelque chose de totalement personnalisé via le bouton caddie dans le chat — elle te livrera le contenu et fixera le prix.",
    customOrderBtnLabel: "Commande personnalisée",
    customOrderFormNote: "Décris précisément le genre de vidéo, photo ou audio que tu veux.",
    customOrderFormPh: "Ex : une vidéo de 30 secondes en lingerie rouge, ambiance douce...",
    customOrderSendBtn: "Envoyer la demande",
    customOrderSentToast: "Ta demande a été envoyée !",
    customOrderDeliverTitle: "Livrer cette commande",
    customOrderDeliverBtn: "Livrer au client",
    customOrderDeliveredToast: "Contenu livré !",
    customOrderDeliveredNote: "Commande livrée",
    customOrderPendingNote: "En attente de livraison",
    customOrderViewBtn: "Voir ma commande",
    customOrderUnauthorized: "Lien non autorisé : seule la créatrice concernée peut livrer cette commande.",
    customOrderSavedToPurchases: "Ajouté à tes achats !",
    customOrderPurchasesTitle: "Commandes personnalisées",
    customOrderPurchasesNone: "Aucune commande personnalisée pour l'instant.",
    chatBotBtnLabel: "Message auto & bannière",
    chatBotWelcomeLabel: "Message de bienvenue automatique",
    chatBotWelcomeNote: "Envoyé automatiquement à l'ouverture du chat, jusqu'à 4 fois maximum par personne. Ajoute des emoji pour le rendre plus chaleureux.",
    chatBotWelcomePh: "Ex : Coucou, ravie que tu sois là 💕 Dis-moi ce qui te ferait plaisir...",
    chatBotBannerLabel: "Bannière défilante",
    chatBotBannerNote: "Une série de messages qui défilent en boucle en haut du chat, visibles par la personne avec qui tu discutes.",
    chatBotBannerAddBtn: "Ajouter un message",
    chatBotIntervalLabel: "Intervalle (secondes)",
    levelDesc_diamond: "Un niveau de soutien remarquable envers les créatrices.",
    bioCoverLabel: "Photo/vidéo de présentation du profil",
    bioCoverNote: "Ceci concerne ta page de présentation de profil (différente de la photo/vidéo de couverture de ta carte).",
    bioNarrativeMainTitle: "Profil de la créatrice",
    coverBelongsToShowcaseNote: "Ceci concerne ta page de présentation publique (différente de ta fiche profil).",
    coverPhotoTip: "Une belle photo bien éclairée, sensuelle et attractive pour attirer des intéressés et des followers.",
    mediaCommentsTitle: "Commentaires sur ce contenu",
    bioNarrativePersonalityTitle: "Sa personnalité",
    bioNarrativePassionsTitle: "Ses passions",
    bioNarrativeContentTitle: "Ce qu'elle propose",
    bioNarrativeUniverseTitle: "Son univers",
    bioNarrativeLookingForTitle: "Ce qu'elle recherche",
    bioNarrativeAmbitionsTitle: "Ses ambitions",
    bioNarrativeAudienceTitle: "Où la retrouver",
    reportPrefillMediaComment: "Commentaire sur une photo/vidéo",
    commentReplyBtn: "Répondre",
    vitrineEnterBtn: "Entrer",
    agencyLogout: "Se déconnecter",
    visitorNeedsAccountFavorite: "Inscris-toi gratuitement pour ajouter des créatrices en favoris — bientôt disponible.",
    visitorNeedsAccountChat: "Inscris-toi gratuitement pour envoyer un message à cette créatrice — bientôt disponible.",
    commentModeAnonymous: "Anonyme",
    commentModeVisitor: "Je suis visiteur",
    commentModeMember: "Utiliser mon pseudo",
    commentModeCustom: "Noter un surnom",
    commentNamePh: "Ton prénom ou pseudo",
    commentNameRequired: "Merci d'indiquer ton prénom ou pseudo avant de publier.",
    paidGalleryTitle: "Galerie payante",
    paidGalleryNote: "Vends des photos et vidéos exclusives directement depuis ton espace. Contenu autorisé : lingerie, tenue sexy, danse sensuelle. Aucune nudité.",
    paidSalesLabel: "ventes",
    paidTotalRevenue: "Chiffre d'affaires total",
    paidTotalSales: "Ventes totales",
    paidAddPhoto: "+ Photo payante",
    paidAddVideo: "+ Vidéo payante",
    paidNoItems: "Aucun contenu payant pour le moment.",
    paidOrdersTitle: "Demandes de déblocage",
    paidOrdersLoading: "Chargement…",
    paidDescLabel: "Description",
    paidDescPh: "Décris ce contenu pour donner envie…",
    paidPriceLabel: "Prix (€)",
    paidTeaserLabel: "Teaser (5 secondes, visible gratuitement)",
    paidFullVideoLabel: "Vidéo complète (verrouillée)",
    paidPhotoLabel: "Photo (verrouillée)",
    paidFileRequired: "Ajoute un fichier avant d'enregistrer.",
    paidTeaserRequired: "Le teaser est obligatoire pour une vidéo payante.",
    paidNoOrders: "Aucune demande en attente.",
    paidMarkPaid: "Marquer payée",
    paidMarkedPaidToast: "Vente confirmée !",
    paidExclusiveTitle: "Contenu exclusif",
    paidExclusiveNote: "Aperçu gratuit ci-dessous, contenu complet à débloquer.",
    exclusiveSalesCount: "déjà débloqué {count} fois",
    paidTeaserBadge: "Teaser gratuit",
    paidUnlockBtn: "Débloquer pour",
    paidLockedPhoto: "Photo exclusive verrouillée",
    paidUnlockExplain: "Envoie ta demande : tu recevras les instructions de paiement, et le contenu te sera transmis une fois le paiement confirmé.",
    paidContactLabel: "Contact (email, téléphone ou WhatsApp)",
    paidContactPh: "ex. email ou numéro WhatsApp",
    paidContactRequired: "Merci d'indiquer ton prénom et un moyen de te contacter.",
    paidSendRequest: "Envoyer la demande",
    paidRequestSent: "Demande envoyée ! Tu vas être contactée pour le paiement.",
    paidPendingAgency: "En attente de validation par l'agence",
    paidSplitLabel: "Répartition :",
    paidSplitCreator: "part créatrice",
    paidInvoiceAndValidate: "Facturer & valider",
    paidPaymentInstructionsIntro: "Ta demande a bien été enregistrée. Effectue le virement ci-dessous en indiquant la référence, puis tu recevras le contenu une fois le paiement confirmé.",
    paidRefLabel: "Référence",
    paidAmountLabel: "Montant",
    paidHolderLabel: "Titulaire du compte",
    paidSalesPanelBtn: "Ventes",
    paidSalesPanelTitle: "Ventes en attente",
    paidVideoPrompt: "Cliquez pour choisir une vidéo",
    paidThisMonthLabel: "Ce mois-ci",
    paidAllTimeLabel: "Total cumulé (tous les mois)",
    toolsTitle: "Outils",
    toolsNote: "Ton espace personnel : calendrier, notes, calculatrice, suivi de tes recettes/dépenses et conseils pratiques. Ces données restent sur ton téléphone, elles ne sont pas partagées.",
    toolCalendar: "Calendrier",
    toolNotes: "Notes",
    toolCalc: "Calculatrice",
    toolFinance: "Finances",
    toolAdvice: "Conseils",
    toolBanner: "Bannière",
    toolBannerNote: "Programme une bannière (date, heure, durée) qui s'affichera sur ta fiche publique pour inviter tes abonné(e)s à t'envoyer un cadeau — anniversaire, Saint-Valentin, Noël, Nouvel An, ou un message 100% à toi.",
    bannerActiveLabel: "Bannière active",
    bannerActiveUntil: "Jusqu'au",
    bannerRemoveBtn: "Retirer la bannière",
    bannerRemoveConfirm: "Retirer la bannière en cours ?",
    bannerTemplateLabel_birthday: "Anniversaire",
    bannerTemplateLabel_valentine: "Saint-Valentin",
    bannerTemplateLabel_christmas: "Noël",
    bannerTemplateLabel_newyear: "Nouvel An",
    bannerTemplateLabel_custom: "Personnalisé",
    bannerTemplate_birthday: "🎂 C'est bientôt mon anniversaire ! Si le cœur t'en dit, un petit cadeau me ferait très plaisir 💛",
    bannerTemplate_valentine: "💘 Joyeuse Saint-Valentin ! Envoie-moi un petit cadeau pour me montrer ton amour 😘",
    bannerTemplate_christmas: "🎄 Joyeux Noël ! Un petit cadeau sous le sapin pour moi ferait battre mon cœur 🎁",
    bannerTemplate_newyear: "🎆 Bonne année ! Commence l'année en beauté en m'offrant un petit cadeau ✨",
    bannerTemplate_custom: "",
    bannerMessageLabel: "Ton message",
    bannerMessagePh: "Écris ce que tu veux — avec ton nom, ou pas, comme tu préfères…",
    bannerDateLabel: "Date de lancement",
    bannerTimeLabel: "Heure",
    bannerDurationLabel: "Durée d'affichage",
    bannerDuration1Day: "1 jour",
    bannerDuration3Days: "3 jours",
    bannerDuration7Days: "7 jours",
    bannerDuration14Days: "14 jours",
    bannerPublishBtn: "Lancer la bannière",
    bannerMessageRequired: "Écris d'abord ton message.",
    bannerDateRequired: "Choisis une date et une heure valides.",
    bannerPublishedToast: "Bannière programmée !",
    bannerViewerCta: "Envoyer un cadeau",
    tierNudgeMessage: "Pense à publier une vidéo exclusive pour remercier tes abonné(e)s de t'avoir aidée à franchir ce cap 💛",
    tierNudgeDismissBtn: "Compris",
    toolIdeas: "Idées Honeymoon",
    ideasIntroTitle: "Bienvenue dans ton espace pro",
    ideasIntroBody: "En rejoignant Honeymoon, tu lances ta propre activité : tu es une créatrice de contenu pour adultes indépendante et auto-entrepreneuse. C'est ton business — à toi de le faire vivre avec sérieux et professionnalisme envers tes abonné(e)s, pour qu'ils reviennent et te soutiennent. Ces idées viennent de la direction et de l'équipe Honeymoon, pour t'aider à en tirer le meilleur.",
    ideasWelcomeTitle: "Message de bienvenue automatique",
    ideasWelcomeNote: "Dès qu'un membre commence à te suivre, ce message lui est envoyé automatiquement et gratuitement dans le chat — une belle première impression, sans effort de ta part.",
    ideasWelcomePh: "Ex. : Merci de me suivre 💛 N'hésite pas à m'écrire, je réponds à tout le monde !",
    ideasWelcomeSaveBtn: "Enregistrer le message",
    ideasWelcomeSavedToast: "Message de bienvenue enregistré !",
    ideasTierTitle: "Paliers de popularité",
    ideasTierBody: "À chaque nouveau palier atteint (bronze, argent, or…), tu recevras un petit rappel dans l'onglet Popularité te suggérant de publier un contenu exclusif pour remercier tes abonné(e)s d'avoir contribué à cette étape.",
    ideasTipsTitle: "Conseils pour animer ta communauté",
    ideasTipsNote: "Ce sont des conseils, pas des obligations — prends ce qui te correspond.",
    ideasTip1: "Réponds à tes messages régulièrement : la réactivité fidélise plus que la quantité de contenu.",
    ideasTip2: "Garde un rythme de publication régulier plutôt que de grosses pauses suivies de rafales.",
    ideasTip3: "Réserve un petit quelque chose (photo, vidéo, message vocal) aux abonné(e)s les plus fidèles.",
    ideasTip4: "Reste toi-même : une personnalité reconnaissable fidélise mieux qu'un contenu générique.",
    ideasTip5: "Fixe tes limites clairement dès le départ — ça évite les malentendus et instaure le respect.",
    audioClearBtn: "Retirer l'audio",
    ideasWelcomeAudioLabel: "Message vocal (optionnel)",
    bannerAudioLabel: "Message vocal (optionnel)",
    bannerColorBgLabel: "Couleur de fond",
    bannerColorTextLabel: "Couleur du texte",
    bannerScrollLabel: "Défilant",
    bannerBlinkLabel: "Clignotant",
    bannerScrollDurationLabel: "Durée du défilement (secondes)",
    toolCalendarPh: "Ajoute une note pour ce jour…",
    toolNotesPh: "Écris ce que tu veux ici…",
    toolCalcError: "Erreur",
    toolIncome: "Recettes",
    toolExpense: "Dépenses",
    toolBalance: "Solde",
    toolFinLabelPh: "Nom (ex. Achat éclairage)",
    toolAddEntry: "Ajouter",
    toolNoEntries: "Aucune entrée pour le moment.",
    toolPaymentAccessNote: "Ces boutons ouvrent les sites officiels PayPal et M-Pesa dans ton navigateur — le site ne peut pas accéder à tes comptes directement.",
    toolFinMissing: "Merci de remplir un nom et un montant valide.",
    toolEstimateEarnings: "Estimer mes gains",
    toolEstimatorIntro: "Dis-moi combien tu vends chaque contenu et combien tu penses en vendre par mois, je calcule une estimation.",
    toolEstimatorPrice: "Prix moyen par contenu (€)",
    toolEstimatorVolume: "Ventes estimées par mois",
    toolEstimatorCalc: "Calculer mon estimation",
    toolEstimatorResult: "Avec un prix moyen de {monthly}€ de chiffre d'affaires estimé ce mois-ci, ta part (à {percent}%) serait d'environ {share}€. C'est une estimation simple — le montant réel dépend de ta demande, de la qualité de ton contenu et de ta régularité.",
    toolCalcReasonPh: "Raison du calcul (ex. budget mensuel)",
    toolCalcHistory: "Historique des calculs",
    toolCalcNoReason: "Sans titre",
    toolCalcNoResult: "Fais d'abord un calcul avant d'enregistrer.",
    toolChatLang: "Langue du chat",
    toolAskAnything: "Pose ta question avec tes mots…",
    toolNoMatch: "Je n'ai pas de réponse toute prête pour ça — essaie de reformuler, ou choisis un sujet dans la liste ci-dessus.",
    paidAddAudio: "+ Message audio",
    paidAudioLabel: "Message audio (verrouillé)",
    paidAudioPrompt: "Cliquez pour choisir un fichier audio",
    paidAudioDescPh: "Sujet du message (ex. un mot doux, un défi, une confidence…)",
    toolDailyBudgetTitle: "Budget quotidien",
    toolDailyBudgetNote: "Combien tu peux dépenser par jour sans risquer le découvert, selon ton solde actuel.",
    toolDailyBudgetDays: "Nombre de jours restants",
    toolDailyBudgetCalc: "Calculer",
    toolDailyBudgetResult: "Tu peux dépenser environ {amount}€ par jour pendant {days} jours sans passer en négatif.",
    toolDailyBudgetNegative: "Ton solde est déjà négatif ou nul — évite toute dépense pour l'instant.",
    toolTaxNotice: "Important : selon ton pays, les revenus que tu gagnes ici peuvent être soumis à l'impôt et à des déclarations obligatoires (activité indépendante, micro-entreprise, etc.). Renseigne-toi auprès de l'administration fiscale de ton pays pour connaître tes obligations exactes et éviter les mauvaises surprises sur ce que tu gardes réellement. Si aucune règle fiscale ne s'applique à ta situation, ce message ne te concerne pas.",
    toolCurrency: "Devise",
    toolCompareCurrencies: "Comparer les devises",
    toolCurrencyLoading: "Chargement des taux…",
    toolCurrencyComparedTo: "Taux par rapport au",
    toolCurrencyDate: "Taux du",
    toolCurrencyError: "Impossible de charger les taux (vérifie ta connexion internet).",
    paidAudioImport: "Importer un fichier",
    paidAudioRecordNow: "Enregistrer maintenant",
    paidAudioRecordPrompt: "Appuie pour commencer à enregistrer",
    paidAudioRecording: "Enregistrement en cours… appuie pour arrêter",
    paidAudioRecordDone: "Enregistrement terminé — écoute-le ci-dessous",
    paidAudioMicError: "Impossible d'accéder au microphone. Vérifie les autorisations de ton navigateur.",
    captureNowBtn: "Prendre maintenant",
    importFileBtn: "Importer un fichier",
    filesSelected: "fichiers sélectionnés",
    paidSeeInMyCurrency: "Voir dans ma devise",
    paidSplitBreakdown: "Répartition du paiement",
    paidSplitPlatform: "part Honeymoon",
    legalLink2257: "Mention 2257",
    legalLinkTerms: "CGU",
    legalLinkPrivacy: "Confidentialité",
    legalLinkPricing: "Prix & remboursement",
    legalDocTitle2257: "Mention légale 2257",
    legalDocTitleTerms: "Conditions générales d'utilisation",
    legalDocTitlePrivacy: "Politique de confidentialité",
    legalDocTitlePricing: "Politique de prix et de remboursement",
    burgerHome: "Accueil",
    burgerTagline: "Univers exclusif de créatrices",
    burgerSectionInfo: "Informations",
    burgerSectionAccount: "Compte",
    burgerCreatorLogin: "Connexion espace créatrice",
    burgerAgencyLogin: "Accès privé agences",
    burgerBecomeMember: "Devenir membre",
    burgerApplyModel: "Postuler pour être modèle",
    burgerFaq: "FAQ",
    burgerRules: "Règles du site",
    legalDocTitleRules: "Règles du site",
    soonBecomeMemberTitle: "Devenir membre — bientôt disponible",
    soonBecomeMemberBody: "Cette fonctionnalité arrive bientôt. Reviens vite pour découvrir comment rejoindre la communauté Honeymoon en tant que membre.",
    memberFreeBadge: "Compte 100% gratuit — sans frais d'inscription",
    memberLoginTitle: "Se connecter",
    memberSignupTitle: "Créer un compte membre",
    memberSignupLine: "Discute avec tes créatrices favorites et débloque leur Tip Menu. Compte gratuit — tu ne payes que ce que tu choisis d'acheter.",
    memberHomeWelcomeLine: "Suis tes créatrices favorites, discute avec elles, et retrouve tous tes achats ici.",
    memberDiscoverCreatorsBtn: "Découvrir les créatrices",
    memberIdentifierLabel: "Nom d'utilisateur ou email",
    memberIdentifierPh: "ton_pseudo ou ton@email.com",
    memberUsernameLabel: "Nom d'utilisateur",
    memberUsernamePh: "Choisis un pseudo",
    memberEmailLabel: "Email",
    memberEmailPh: "ton@email.com",
    memberPasswordLabel: "Mot de passe",
    memberPasswordPh: "Choisis un mot de passe (6 caractères min.)",
    memberPasswordLoginPh: "Ton mot de passe",
    memberConfirmPasswordLabel: "Confirme le mot de passe",
    memberConfirmPasswordPh: "Retape le mot de passe",
    memberLoginBtn: "Se connecter",
    memberSignupBtn: "Créer mon compte",
    memberNoAccount: "Pas encore de compte ?",
    memberCreateOne: "Crée-en un",
    memberHaveAccount: "Déjà membre ?",
    memberLoginInstead: "Connecte-toi",
    memberForgotLink: "Mot de passe ou nom d'utilisateur oublié ?",
    memberBackToLogin: "← Retour à la connexion",
    memberErrFillAll: "Merci de remplir tous les champs.",
    memberErrPassMismatch: "Les mots de passe ne correspondent pas.",
    memberErrPassShort: "Le mot de passe doit faire au moins 6 caractères.",
    memberErrUsernameTaken: "Ce nom d'utilisateur est déjà pris.",
    memberErrUsernameFormat: "Le nom d'utilisateur doit faire 3 à 20 caractères (lettres, chiffres, points, tirets, underscores).",
    memberErrEmailInUse: "Un compte existe déjà avec cet email.",
    memberErrInvalidEmail: "Adresse email invalide.",
    memberErrWeakPass: "Ce mot de passe est trop faible.",
    memberErrLoginFailed: "Identifiant ou mot de passe incorrect.",
    memberErrUnknown: "Une erreur est survenue. Réessaie.",
    memberErrNoConnection: "Connexion au serveur indisponible — recharge la page et réessaie.",
    memberVerifyTitle: "Confirme ton compte",
    memberVerifyBody: "Un email de confirmation vient d'être envoyé à {email}. Ouvre-le et clique sur le lien pour activer ton compte membre. Pense à vérifier tes spams si tu ne le vois pas.",
    memberVerifyCheckBtn: "J'ai confirmé, continuer",
    memberVerifyResendBtn: "Renvoyer l'email de confirmation",
    memberVerifyResendToast: "Email de confirmation renvoyé.",
    memberVerifyStillPending: "Ton compte n'est pas encore confirmé. Vérifie ta boîte mail (et tes spams), puis clique sur le lien reçu avant de continuer.",
    memberVerifyLogout: "Se déconnecter",
    memberHomeWelcome: "Bienvenue, {username} !",
    memberHomeConfirmed: "Ton compte membre est actif et confirmé.",
    memberHomeSoon: "L'espace membre (contenus, abonnements...) arrive très bientôt. Reviens vite !",
    memberHomeLogout: "Se déconnecter",
    memberLoggedOutToast: "Tu es déconnecté(e).",
    memberSignupSuccessToast: "Compte créé avec succès.",
    memberForgotTitle: "Mot de passe ou identifiant oublié",
    memberForgotBody: "Indique l'email associé à ton compte. Si un compte existe, tu recevras un lien pour réinitialiser ton mot de passe (ton nom d'utilisateur te sera rappelé une fois connecté).",
    memberForgotEmailPh: "ton@email.com",
    memberForgotSendBtn: "Envoyer le lien",
    memberForgotSentTitle: "Email envoyé",
    memberForgotSentBody: "Si un compte existe avec cet email, un lien de réinitialisation vient d'être envoyé. Ouvre-le pour choisir un nouveau mot de passe.",
    memberTabProfile: "Profil",
    memberTabPurchases: "Mes achats",
    memberUnverifiedBanner: "Compte pas encore confirmé — email envoyé à {email}.",
    memberResendShort: "Renvoyer",
    memberResentShort: "Renvoyé ✓",
    memberAvatarChange: "Changer la photo",
    memberLocationLabel: "Localisation",
    memberLocationPh: "Ville, pays...",
    memberBioLabel: "Biographie",
    memberBioPh: "Parle un peu de toi...",
    caThisMonthShort: "CA du mois",
    coverVideoBtn: "Mini-vidéo",
    coverVideoNote: "Tu peux mettre une photo, ou une mini-vidéo de présentation — ça attire souvent plus de vues et d'abonnés.",
    coverVideoRules: "Vidéo de 60 secondes maximum. Pas de nudité — lingerie ou tenue sexy uniquement, comme pour tes photos. Pas de gestes sexuels explicites (mime de doigtage, etc.) — le twerk, la danse et les poses sensuelles restent acceptés. Le sensuel est bienvenu, mais jamais la simulation d'un acte sexuel.",
    coverVideoTooLong: "Cette vidéo dépasse 60 secondes — choisis-en une plus courte.",
    levelDescPrefix: "Niveau",
    levelDesc_gray: "Le point de départ de toutes les créatrices.",
    levelDesc_bronze: "Une première communauté commence à se former autour de toi.",
    levelDesc_silver: "Ta popularité grandit, de plus en plus de membres te suivent.",
    levelDesc_gold: "Tu fais partie des créatrices bien établies sur Honeymoon.",
    levelDesc_purple: "Une forte communauté te soutient activement.",
    levelDesc_red: "Le niveau maximum — tu fais partie des créatrices les plus populaires du site.",
    publicIntroLabel: "Décris-nous qui tu es pour le public",
    publicIntroNote: "10 lignes maximum. Ce texte s'affichera sur ta page publique, sous tes abonnés.",
    publicIntroPh: "Ex : Je suis passionnée de danse et j'adore partager des moments coquins avec vous...",
    myFamilyPopularity: "Popularité",
    popularityTabNote: "Ton badge de popularité, tes abonné(e)s et les personnes que tu suis.",
    followingLabel: "Abonnements",
    followersLabel: "Abonnés",
    likesLabel: "Likes",
    followersListTitle: "Abonné(e)s",
    followingListTitle: "Abonnements",
    tierLabel_gray: "Débutant",
    tierLabel_bronze: "Bronze",
    tierLabel_silver: "Argent",
    tierLabel_gold: "Or",
    tierLabel_red: "Top créatrice",
    tierLabel_purple: "Violet",
    tierLabel_diamond: "Diamant",
    uxdLabel: "UXD",
    uxdExplainNote: "UXD, ton grade de statut sur Honeymoon. Chaque soutien te fait progresser vers un rang reconnu par toute la communauté — jusqu'au niveau le plus élevé.",
    uxdLevelDesc_gray: "Le point de départ de tout nouveau membre.",
    uxdLevelDesc_silver: "Tu commences à te démarquer parmi les fans.",
    uxdLevelDesc_bronze: "Ton statut grimpe, tu entres dans le cercle des membres reconnus.",
    uxdLevelDesc_gold: "Tu fais partie des membres les plus en vue de la communauté.",
    uxdLevelDesc_purple: "Un rang d'élite, réservé à une poignée de membres.",
    uxdLevelDesc_red: "Le rang suprême — ton statut est au sommet de Honeymoon.",
    tipMenuTabLabel: "Tip Menu",
    tipMenuTabNote: "Remplis ton menu par thème (photo, vidéo, audio). Les prix sont fixés par la plateforme — choisis-les dans la liste. Publie pour qu'il apparaisse sur ta page.",
    tipMenuThemePh: "Nom du thème (ex : lingerie)",
    tipMenuColTheme: "Thème",
    tipMenuColPhoto: "Photo",
    tipMenuColVideo: "Vidéo",
    tipMenuColAudio: "Audio",
    tipMenuNoPrice: "—",
    tipMenuAddRow: "Ajouter un thème",
    tipMenuRulesLabel: "Explique les règles de chaque thème",
    tipMenuRulesPh: "Ex : Lingerie = photo en lingerie fine, pas de nudité. Danse sensuelle = vidéo 30-60s...",
    tipMenuPriceLockedNote: "Les prix sont fixés par Honeymoon — tu ne peux choisir que parmi les montants proposés.",
    tipMenuPublishBtn: "Publier sur ma page",
    tipMenuPublishedToast: "Tip Menu publié sur ta page !",
    tipMenuCustomNote: "Une envie particulière ? Demande personnalisée à discuter directement dans le chat.",
    tipMenuRowExplain: "Pour chaque ligne : choisis le type de contenu (photo, vidéo ou audio), donne un thème, un prix, et une description de ce que ça inclut.",
    tipMenuPriceLabel: "Prix",
    tipMenuDescLabel: "Description (ce que ça inclut)",
    tipMenuDescPh: "Ex : vidéo de 30 secondes, tenue en lingerie noire, sans nudité.",
    tipMenuEditRow: "Modifier",
    tipMenuRowDoneBtn: "Valider cette ligne",
    tipMenuThemeRequired: "Ajoute un nom de thème avant de valider.",
    tipMenuHelpTheme: "Le nom de ce que tu proposes, par exemple \"Lingerie rouge\" ou \"Danse sensuelle\".",
    tipMenuHelpPrice: "Choisis un prix entre {min}€ et {max}€ pour ce type de contenu. Si tu dépasses le maximum autorisé, il sera automatiquement ramené à {max}€.",
    tipMenuHelpDesc: "Décris en quelques mots ce qui est inclus (durée, tenue, ce qui est montré ou non). 20 mots maximum.",
    tipMenuPriceClamped: "Prix ramené au maximum autorisé : {max}€.",
    tipMenuHelpEmoji: "Tu peux mettre un ou plusieurs emojis, ou laisser vide — l'emoji par défaut peut être effacé.",
    tipMenuMaxRows: "Maximum 25 lignes dans ton Tip Menu.",
    tipMenuTheme_lingerie: "Lingerie",
    tipMenuTheme_danse_sensuelle: "Danse sensuelle",
    tipMenuTheme_strip_tease: "Strip-tease",
    tipMenuTheme_pov_intime: "POV intime",
    tipMenuTheme_roleplay: "Jeu de rôle",
    tipMenuTheme_fetish_pieds: "Fétiche pieds",
    tipMenuTheme_costume_theme: "Costume à thème",
    tipMenuTheme_exterieur: "Extérieur",
    tipMenuTheme_duo_couple: "Duo / couple",
    tipMenuTheme_demande_personnalisee: "Demande personnalisée",
    followBtn: "Suivre",
    followingBtn: "Suivi(e)",
    membersViewerBtn: "Membres",
    membersViewerTitle: "Membres qui partagent leur profil",
    membersViewerEmpty: "Aucun membre ne partage sa bio ou ses photos pour le moment.",
    myMembersTabNote: "Retrouve ici les membres qui ont choisi de partager leur bio ou leurs photos avec toi, ceux que tu suis, et tes favoris.",
    myMembersFilterAll: "Tous",
    myMembersFilterFavorites: "Favoris",
    myMembersNoFavorites: "Aucun favori pour le moment.",
    myMembersFavoriteBtn: "Favori",
    myMembersUnfavoriteBtn: "Retirer",
    memberVisibilityLabel: "Qui peut voir",
    memberVisibilityEveryone: "Toutes les créatrices",
    memberVisibilityFavorites: "Uniquement mes favoris",
    memberVisibilityNobody: "Personne",
    memberBioVisibleLabel: "Rendre ma bio visible par la créatrice",
    memberSubtabInfos: "Mes infos",
    memberSubtabPhotos: "Mes photos",
    memberSubtabPassword: "Mot de passe",
    memberPrivateFieldNote: "Jamais visible par personne d'autre que toi.",
    memberBioVisibilityExplain: "Selon ton choix ci-dessus, ta bio peut être vue par les créatrices concernées. Le reste de ton profil (email, achats, mot de passe) n'est, lui, jamais visible.",
    memberPhotosVisibilityExplain: "Selon ton choix ci-dessus, ces photos peuvent être vues par les créatrices concernées. Elles sont toujours séparées de tes achats.",
    memberBioHiddenNote: "Ta bio n'est visible que par toi. Le reste de ton profil (email, achats, mot de passe...) n'est jamais visible ni par les créatrices ni par les autres membres.",
    memberSaveBtn: "Enregistrer",
    memberSavedToast: "Modifications enregistrées.",
    memberChangePasswordTitle: "Changer le mot de passe",
    memberCurrentPasswordLabel: "Mot de passe actuel",
    memberCurrentPasswordPh: "Ton mot de passe actuel",
    memberNewPasswordLabel: "Nouveau mot de passe",
    memberNewPasswordPh: "Nouveau mot de passe (6 caractères min.)",
    memberChangePasswordBtn: "Mettre à jour le mot de passe",
    memberPasswordChangedToast: "Mot de passe mis à jour.",
    memberErrWrongCurrentPass: "Mot de passe actuel incorrect.",
    memberPurchaseHistoryTitle: "Historique de paiement",
    memberPurchaseNone: "Aucun achat pour le moment.",
    memberPurchasePending: "en attente",
    memberPurchasePaid: "payé",
    memberPurchasePhotosTitle: "Photos achetées",
    memberPurchaseVideosTitle: "Vidéos achetées",
    memberPurchaseNoPhotos: "Aucune photo achetée pour le moment.",
    memberPurchaseNoVideos: "Aucune vidéo achetée pour le moment.",
    memberPurchaseLoadErr: "Impossible de charger tes achats pour le moment. Réessaie plus tard.",
    applyTitle: "Postuler pour être modèle",
    applyIntro: "Ce formulaire est ouvert à toutes. Remplis-le et il sera envoyé directement à l'équipe Honeymoon — aucun frais, aucune obligation.",
    applyBusinessPitch: "Rejoindre Honeymoon, c'est lancer ta propre activité : tu gères ton business comme une créatrice de contenu indépendante et auto-entrepreneuse, à ton rythme et à tes conditions.",
    applyNameLabel: "Nom / pseudo souhaité",
    applyNamePh: "Ton prénom ou le pseudo que tu veux utiliser",
    applyContactEmailLabel: "Email de contact",
    applyContactEmailPh: "ton@email.com",
    applyContactPhoneLabel: "Téléphone / autre contact (optionnel)",
    applyContactPhonePh: "WhatsApp, Telegram, numéro...",
    applyCountryLabel: "Pays / localisation",
    applyCountryPh: "Ville, pays",
    applyWorkingElsewhereLabel: "Travailles-tu déjà sur un autre site ou avec une autre agence ?",
    applyWorkingElsewhereNo: "Non, aucune",
    applyWorkingElsewhereYes: "Oui",
    applyWorkingElsewhereDetailLabel: "Nom du site / agence + ton ID ou pseudo là-bas",
    applyWorkingElsewhereDetailPh: "Ex : NomDuSite — pseudo123",
    applyMotivationLabel: "Pourquoi veux-tu rejoindre Honeymoon ?",
    applyMotivationPh: "Ta motivation, ce que tu recherches, ta disponibilité...",
    applySocialLabel: "Réseaux sociaux / portfolio (optionnel)",
    applySocialPh: "Instagram, TikTok, lien vers tes photos...",
    applyLegalTitle: "Conditions du site",
    applyLegalText: "Honeymoon fonctionne avec un contrat de collaboration (non exclusif sauf accord séparé) : contenu autorisé limité à lingerie / tenue sexy / danse sensuelle — aucun contenu nu n'est accepté sur cette plateforme. Pour tout contenu payant vendu, la répartition est de 60% pour la créatrice et 40% pour Honeymoon au titre de la gestion de la plateforme. Une vérification d'identité et d'âge (18 ans minimum) est obligatoire avant toute publication. Le contrat complet est présenté et signé électroniquement si ta candidature est retenue.",
    applyCheck18: "Je confirme avoir 18 ans ou plus.",
    applyCheckConditions: "J'ai lu et j'accepte les conditions ci-dessus (contenu autorisé, répartition 60/40, vérification d'identité).",
    applyCheckData: "J'accepte que mes informations soient transmises à l'équipe Honeymoon dans le cadre de l'étude de ma candidature.",
    applySendBtn: "Envoyer ma candidature",
    applyErrFillRequired: "Merci de remplir tous les champs obligatoires.",
    applyErrChecks: "Merci de cocher les 3 cases pour envoyer ta candidature.",
    applySentTitle: "Candidature envoyée !",
    applySentBody: "Merci ! Ta candidature a bien été transmise à l'équipe Honeymoon. Tu seras recontactée directement à l'email ou au contact que tu as indiqué si ton profil est retenu.",
    applySentClose: "Fermer",
    applicationsPanelBtn: "Candidatures",
    applicationsNoneYet: "Aucune candidature pour le moment.",
    memberTabFavorites: "Favoris",
    memberUseMyLocation: "Utiliser ma position",
    memberGeolocLoading: "Localisation en cours…",
    memberGeolocDenied: "Localisation refusée ou indisponible.",
    memberGeolocUnsupported: "La géolocalisation n'est pas disponible sur cet appareil.",
    memberMyPhotosTitle: "Mes photos",
    memberMyPhotosNote: "Des photos personnelles, séparées de tes achats. Choisis ci-dessous si les créatrices peuvent les voir.",
    memberPhotoDeleteBtn: "Supprimer cette photo",
    memberPhotoDeleteConfirm: "Supprimer définitivement cette photo ?",
    memberPhotosVisibleLabel: "Rendre mes photos visibles par les créatrices",
    memberFavoritesNone: "Aucune créatrice en favori pour le moment. Appuie sur le ♡ sur une fiche pour l'ajouter.",
    memberFavoritesHype: "✨ Tes coups de cœur, réunis ici — ne rate plus jamais leurs nouveautés.",
    memberMessagesHype: "💬 Un message, une connexion. Elles adorent te lire.",
    memberFavoriteToggle: "Ajouter/retirer des favoris",
    memberFavoriteAdded: "Ajoutée à tes favoris.",
    memberFavoriteRemoved: "Retirée de tes favoris.",
    myCommentsTitle: "Commentaires reçus",
    myCommentsNote: "Les commentaires laissés sur ta fiche par les visiteurs. Tu peux supprimer un commentaire que tu juges déplacé ou outrageant.",
    myCommentsNone: "Aucun commentaire pour le moment.",
    myCommentsDelete: "Supprimer ce commentaire",
    myCommentsConfirmDelete: "Supprimer définitivement ce commentaire ?",
    myCommentsReportToTeam: "Signaler à l'équipe",
    logoutConfirm: "Se déconnecter de ton compte membre ?",
    deletionsPanelBtn: "Suppressions",
    deletionsNoneYet: "Aucune demande de suppression pour le moment.",
    deletionStatusCancelled: "annulée",
    deletionStatusCompleted: "supprimé",
    deletionEligibleNow: "délai écoulé — prêt",
    deletionDaysLeft: "encore {n} jour(s)",
    deletionConfirmBtn: "Supprimer définitivement",
    deletionFinalConfirm: "Supprimer DÉFINITIVEMENT le compte de {name} et tout son contenu ? Cette action est irréversible.",
    deletionCompletedToast: "Compte supprimé définitivement.",
    creatorRulesArticleTitle: "Règles, droits et devoirs",
    creatorRulesArticleBody: "En tant que créatrice sur Honeymoon, tu conserves 60% de tes ventes de contenu payant (40% pour la gestion de la plateforme). Le contenu autorisé se limite à la lingerie, tenue sexy et danse sensuelle — aucun contenu nu n'est accepté. Une pièce d'identité valide est obligatoire avant toute publication. Tu restes libre de gérer ton contenu, et tu peux demander la suppression de ton compte à tout moment ci-dessous.\n\nSuppression de compte : une fois ta demande envoyée avec un délai (1 à 7 jours) et ta raison, l'équipe Honeymoon est notifiée. Tu peux annuler ta demande à tout moment tant que le délai n'est pas écoulé. Passé ce délai, la suppression devient possible et ton profil, tes photos, vidéos et commentaires sont définitivement effacés.",
    deletionPendingBanner: "Suppression de ton compte prévue dans {n} jour(s).",
    deletionCancelBtn: "Annuler la demande",
    deletionCancelledToast: "Demande de suppression annulée.",
    deletionOpenBtn: "Supprimer mon compte créatrice",
    deletionDelayLabel: "Délai avant suppression",
    deletionDelayOption: "{n} jour(s)",
    deletionReasonLabel: "Raison de la suppression",
    deletionReasonPh: "Explique pourquoi tu souhaites supprimer ton compte...",
    deletionSubmitBtn: "Envoyer la demande",
    deletionRequestedToast: "Demande de suppression envoyée.",
    memberDeleteAccountTitle: "Supprimer mon compte",
    memberDeleteAccountNote: "Cette action supprime définitivement ton compte membre, ton profil et tes photos personnelles. Un email de confirmation te sera envoyé.",
    memberDeleteAccountBtn: "Supprimer mon compte",
    memberDeleteAccountConfirm1: "Es-tu sûr(e) de vouloir supprimer ton compte membre ? Cette action est irréversible.",
    memberDeleteAccountConfirm2: "Dernière confirmation : ton profil, ta bio et tes photos personnelles seront supprimés définitivement. Continuer ?",
    memberDeleteAccountDone: "Ton compte a été supprimé. Un email de confirmation t'a été envoyé.",
    memberDeleteRequiresRecentLogin: "Pour ta sécurité, reconnecte-toi puis réessaie de supprimer ton compte.",
    adminForgotNeedEmail: "Indique d'abord ton email ci-dessus.",
    adminForgotSent: "Un lien de réinitialisation a été envoyé à {email}. Vérifie ta boîte mail.",
    visitorBadgeLabel: "Visiteur",
    memberTabMessages: "Messages",
    myMessagesTitle: "Messages",
    myMessagesNote: "Discute en direct avec les membres qui t'écrivent.",
    chatLoading: "Chargement…",
    chatEmptyNote: "Aucun message pour le moment. Dis bonjour !",
    chatNoOrdersNote: "Aucune commande dans cette conversation pour le moment.",
    chatTabLibre: "Discussion libre",
    chatTabOrders: "Commandes",
    chatTopicStarterTemplate: "On parle de {topic} ? 😊",
    chatTopic_day: "Ta journée",
    chatTopic_travel: "Voyages",
    chatTopic_music: "Musique",
    chatTopic_movies: "Films & séries",
    chatTopic_desires: "Envies",
    chatTopic_compliments: "Compliments",
    chatTopic_teasing: "Petit jeu de taquineries",
    chatTopic_secrets: "Confidences",
    chatTopic_style: "Style",
    chatTopic_dreams: "Rêves",
    chatTopic_humor: "Humour",
    chatTopic_food: "Gourmandises",
    chatTopic_perfectNight: "Soirée idéale",
    chatTopic_memories: "Souvenirs",
    chatTopic_wellness: "Détente",
    chatTopic_nowPlaying: "Ce que tu écoutes",
    chatTopic_common: "Points communs",
    chatTopic_weekend: "Week-end parfait",
    chatTopic_littleSecret: "Un petit secret",
    chatTopic_reunion: "Si on se retrouvait",
    chatNoConversations: "Aucune conversation pour le moment.",
    chatTypingIndicator: "est en train d'écrire…",
    chatRulesBanner: "⚠️ Espace de discussion respectueux : les insultes sont interdites. L'échange de coordonnées personnelles (numéro de téléphone, réseaux sociaux, email) est interdit sur la plateforme et peut entraîner des sanctions. La discussion est libre : les sujets proposés ne sont que des idées, jamais une obligation.",
    chatReportMessage: "Signaler ce message à l'équipe",
    chatDeleteMessage: "Supprimer ce message",
    chatDeleteMessageConfirm: "Supprimer définitivement ce message ?",
    chatStartBtn: "Envoyer un message",
    myFamilyContent: "Contenu",
    myFamilyMessages: "Messages",
    myFamilyCA: "CA & Ventes",
    myFamilyTools: "Outils",
    myFamilyRules: "Règles",
    caTabNote: "Suivi de tes revenus, répartition des paiements et commandes en cours.",
    backToMenu: "Retour au menu",
    burgerLogout: "Déconnexion",
    themeToBordeaux: "Mode sombre",
    themeToLight: "Mode clair",
    soonApplyModelTitle: "Postuler pour être modèle — bientôt disponible",
    soonApplyModelBody: "Cette fonctionnalité arrive bientôt. Reviens vite pour découvrir comment postuler pour rejoindre le catalogue Honeymoon.",
    contractTabLabel: "Contrat",
    creatorContractBtn: "Contrat créatrice",
    creatorContractNameLabel: "Nom de scène",
    creatorContractConsent: "Je certifie avoir lu et j'accepte l'ensemble des conditions de ce contrat.",
    signContractType: "Type de contrat",
    signTypeAgency: "Agence partenaire",
    signTypePartnerSite: "Site partenaire (cam, chat, autre plateforme)",
    signTypeOther: "Autre / contrat vierge",
    signPartnerSiteNameLabel: "Nom du site partenaire",
    signOtherNameLabel: "Nom (agence, personne ou entité)",
    signCustomTextPh: "Écris ici les termes de ce contrat (comme sur une feuille vierge)…",
    paidYouWillEarn: "Tu gagneras environ",
    toolCurrencyOther: "Autre (préciser)",
    toolCurrencyCustomPh: "ex. FCFA, ₦, Rp…",
    paidSeeInGoogle: "Voir la conversion sur Google",
    paidCABrut: "CA Brut",
    paidCANet: "CA Net",
    reportLinkLabel: "🚩 Signaler un contenu",
    reportModalTitle: "Signaler un contenu",
    reportModalNote: "Utilise ce formulaire pour signaler un contenu problématique (mineur suspecté, contenu publié sans consentement, contenu volé, ou autre). Nous traitons chaque signalement en priorité et retirons le contenu concerné dans l'attente d'une vérification.",
    reportWhichProfile: "Créatrice ou page concernée",
    reportWhichProfilePh: "ex. nom de la créatrice ou lien",
    reportReason: "Raison du signalement",
    reportReasonMinor: "Je soupçonne une personne mineure",
    reportReasonNonConsent: "Contenu publié sans consentement",
    reportReasonStolen: "Contenu volé / republié sans autorisation",
    reportReasonHarassment: "Harcèlement / comportement abusif",
    reportReasonScam: "Arnaque / fraude",
    reportReasonImpersonation: "Usurpation d'identité",
    reportReasonViolence: "Violence / menaces",
    reportReasonSpam: "Spam / publicité non sollicitée",
    reportReasonPrivacy: "Atteinte à la vie privée",
    reportReasonOther: "Autre raison",
    reportAttachment: "Pièce jointe (optionnelle)",
    reportDetails: "Détails",
    reportDetailsPh: "Décris précisément le problème…",
    reportContact: "Ton contact (optionnel)",
    reportContactPh: "email ou téléphone, pour te tenir informé·e",
    reportSendBtn: "Envoyer le signalement",
    reportDetailsRequired: "Merci de décrire le problème avant d'envoyer.",
    reportSentToast: "Signalement envoyé. Merci — nous le traitons en priorité.",
    reportsPanelBtn: "Signalements",
    reportsNoneYet: "Aucun signalement pour le moment.",
    reportThisCreatorBtn: "Signaler cette créatrice",
    reportCommentPrefix: "Commentaire signalé de",
    toolAdviceNote: "Clique sur un sujet ci-dessous, le conseil s'affiche comme dans une conversation.",
    showcaseTitle: "Présentation agences",
    showcaseNote: "Contenu réservé à la présentation de la créatrice aux agences partenaires (non visible du grand public).",
    showcasePhotoLabel: "Photo de présentation",
    showcaseShortLabel: "Vidéo courte (showreel)",
    showcaseLongLabel: "Vidéo longue (portfolio)",
    signContractBtn: "Signer un contrat",
    featuredBadge: "En avant",
    featureBtn: "Mettre en avant",
    unfeatureBtn: "Retirer la mise en avant",
    signContractExplain: "En signant, vous confirmez être habilité(e) à engager votre agence dans un contrat de représentation avec cette créatrice, selon les conditions convenues avec Honeymoon.",
    signAgencyName: "Nom de l'agence",
    signRepName: "Nom du représentant",
    signDrawLabel: "Signature (dessinez ci-dessous)",
    signClearBtn: "Effacer",
    signConsentText: "Je certifie être autorisé(e) à signer au nom de mon agence et j'accepte les conditions du contrat.",
    signConfirmBtn: "Signer le contrat",
    signMissingFields: "Merci de remplir le nom de l'agence et du représentant.",
    signMissingSignature: "Merci de dessiner votre signature.",
    signMissingConsent: "Merci de cocher la case de consentement.",
    signCertTitle: "Certificat de signature n°",
    signSavedToast: "Contrat signé et enregistré !",
    signNoContracts: "Aucun contrat signé pour le moment.",
    signViewBtn: "Voir",
    contractsPanelBtn: "Contrats",
    signedContractsTitle: "Contrats signés",
    agencyContractBtn: "Contrat agence",
    signSignatureLabel: "Signature",
    paidWhatsappBtn: "Prévenir Honeymoon sur WhatsApp",
    paidUploadingTeaser: "Envoi teaser…",
    paidUploadingFull: "Envoi vidéo…",
    adminSub: 'Accès administrateur',
    adminEnter: 'Déverrouiller',
    adminCancel: 'Annuler',
    adminErr: 'Code administrateur incorrect.',
    editToggleOn: "CTA",
    editToggleOff: 'Terminé',
    heroEyebrow: 'Catalogue',
    heroTitle: 'créatrices, un contrat, une exigence : <em>le sérieux</em>.',
    heroBody: "Le catalogue Honeymoon réunit 5 créatrices sous contrat exclusif, choisies pour leur sérieux et leur motivation. Certaines débutent dans le milieu : les attentes sont claires dès le départ, et elles s'y tiennent.",
    catalogueTitle: 'Le Catalogue',
    emptyName: 'Profil à venir bientôt',
    emptyDesc: 'Ce profil sera bientôt disponible.',
    nameUndefined: 'Nom à définir',
    platforms: 'Plateformes',
    audience: 'Audience',
    content: 'Contenu',
    verified: '18+ vérifiée',
    notVerified: 'Non vérifiée',
    viewContract: 'Voir le contrat',
    noContract: 'Contrat à venir',
    editProfile: 'Modifier ce profil',
    galleryBtn: 'Galerie',
    galleryTitle: 'Galerie',
    galleryClose: 'Fermer',
    galleryPhotos: 'Photos',
    galleryVideos: 'Vidéos',
    galleryEmpty: 'Aucun média pour le moment.',
    storageFull: "Stockage plein dans ce navigateur — impossible d'ajouter ce fichier. Essaie un fichier plus léger, ou passe à un vrai stockage (backend) pour un catalogue plus complet.",
    contactTitle: 'Intéressé par une collaboration ?',
    contactBody: "Contactez l'équipe Honeymoon pour discuter d'un partenariat, obtenir plus d'informations sur une créatrice ou organiser une présentation.",
    contactBtn: 'Contacter Honeymoon',
    agencyTrustContract: "Contrat signé pour chaque créatrice",
    agencyTrustVerified: "Profils vérifiés 18+",
    agencyTrustCountLabel: "créatrices sous contrat",
    footTag: 'Honeymoon — Confidentiel',
    modalTitle: 'Modifier le profil',
    stageName: 'Nom de scène',
    country: 'Pays',
    platformsPh: 'ex. Instagram · TikTok',
    audiencePh: 'ex. 25K+',
    contentPh: 'ex. Danse · Vidéo · Social',
    availLabel: 'Disponible pour (séparé par des virgules)',
    photoLabel: 'Photo de couverture',
    photoPrompt: 'Cliquez pour choisir une photo',
    photoReplace: 'Photo actuelle — cliquez pour remplacer',
    contractLabel: 'Contrat & consentement (PDF)',
    contractPrompt: 'Cliquez pour ajouter le PDF',
    contractReplace: 'PDF ajouté — cliquez pour remplacer',
    consentText: "Je confirme que cette créatrice est majeure (18+), a signé un contrat et a donné son accord pour l'utilisation de sa photo et de ses informations dans ce catalogue.",
    cancel: 'Annuler',
    save: 'Enregistrer',
    savedToast: 'Profil enregistré (sauvegardé dans ce navigateur)',
    needConsentToast: "Merci de confirmer la majorité, le contrat et l'accord de la créatrice avant d'enregistrer.",
    addedToast: 'Ajouté à la galerie',
    removedToast: 'Supprimé de la galerie',
    creatorLink: 'Espace créatrice',
    vitrineLink: '← Retour',
    ageGateTitle: 'Vérification d\'âge',
    ageGateBody: "Ce site présente du contenu réservé aux personnes majeures (18 ans et plus). Confirmez votre âge pour continuer.",
    ageYes: "Oui, j'ai 18 ans ou plus",
    ageNo: "Non, j'ai moins de 18 ans",
    ageBlockedTitle: 'Accès refusé',
    ageBlockedBody: "L'accès à ce site est réservé aux personnes majeures (18 ans et plus).",
    ageLeaveBtn: 'Quitter',
    creatorGateSub: 'Accès créatrice',
    creatorEnter: 'Entrer',
    backAgency: '← Retour',
    creatorErr: 'Code incorrect.',
    creatorLogout: 'Se déconnecter',
    myProfileHello: 'Bonjour',
    myProfileNote: "Voici ta photo et tes vidéos telles qu'elles apparaissent dans le catalogue. Tu ne peux rien ajouter ni modifier ici — pour un changement, contacte l'équipe Honeymoon.",
    myProfilePhotos: 'Tes photos',
    myProfileVideos: 'Tes vidéos',
    myProfileNoMedia: 'Aucun média ajouté pour le moment.',
    creatorCodeLabel: 'Code créatrice (à lui transmettre)',
    copyBtn: 'Copier',
    copiedToast: 'Code copié',
    numberPrefix: 'N°',
    myEditBtn: 'Modifier mes informations',
    myProfileManageNote: "Gère ta photo, tes informations et ta galerie ci-dessous. Les photos et vidéos que tu postes ici seront visibles sur le site vitrine.",
    addPhoto: 'Ajouter des photos',
    addVideo: 'Ajouter des vidéos',
    uploadingLabel: 'Envoi en cours…',
    uploadFailed: "Échec de l'envoi.",
    saveErrorToast: "Erreur lors de l'enregistrement — vérifie ta connexion et réessaie.",
    myVaultTitle: 'Mon coffre personnel',
    myVaultNote: "Un espace privé pour sauvegarder tes photos et vidéos. Contrairement à ta galerie ci-dessus, ce coffre n'est visible par personne d'autre que toi.",
    myVaultPhotos: 'Photos sauvegardées',
    myVaultVideos: 'Vidéos sauvegardées',
    bioSectionTitle: 'Biographie',
    bioSectionNote: "Ces informations serviront à présenter la créatrice sur le site vitrine.",
    bioOrigin: 'Origine',
    bioNationality: 'Nationalité',
    bioAge: 'Âge',
    bioBodyType: 'Type de corps',
    bioOrientation: 'Orientation',
    bioLookingFor: 'Ce qu\'elle recherche',
    bioPassions: 'Passions',
    bioUniverse: 'Son univers',
    bioHobbies: 'Hobbies',
    bioPersonality: 'Personnalité',
    bioFantasies: 'Fantasmes',
    bioFetish: 'Fetish',
    bioAmbitions: 'Ambitions',
    bioSocials: 'Réseaux sociaux (optionnel)',
    bioSocialsPh: 'ex. Instagram @..., TikTok @...',
    bioWorkUrl: 'Site où elle travaille (lien)',
    bioWorkUrlPh: 'https://...',
    bioOnlineStatus: 'Statut',
    statusOnline: 'En ligne',
    statusOffline: 'Hors ligne',
    contentPolicyNote: "Photos et vidéos : lingerie ou tenue sexy uniquement (danse, twerk, sensuel, aguicheur autorisés). Aucun contenu nu — photo ou vidéo — n'est accepté.",
    vitrineHeroEyebrow: 'Bienvenue chez Honeymoon',
    vitrineHeroTitle: 'Tes envies, nos <em>créatrices professionnelles</em>',
    vitrineHeroBody: "Des créatrices actives et expérimentées, entièrement dédiées à toi. Aime, commente, découvre leur univers.",
    vitrineHeroCta: "Rejoindre",
    vitrineHeroTrustSuffix: "créatrices actives",
    vitrineBack: '← Retour',
    vitrineEmpty: 'Aucune créatrice publiée pour le moment.',
    visitSiteBtn: 'Visiter son site',
    likeLabel: "J'aime",
    dislikeLabel: "Je n'aime pas",
    commentsTitle: 'Commentaires',
    commentPlaceholder: 'Écris un commentaire respectueux…',
    commentSubmit: 'Publier',
    commentEmpty: 'Aucun commentaire pour le moment. Sois la première !',
    commentModerationError: "Ton commentaire contient des mots non autorisés (insultes, grossièretés). Merci de le reformuler.",
    commentPosted: 'Commentaire publié',
    commentRules: "Espace de commentaires bienveillant : pas d'injures, pas de grossièretés.",
    commentsCommunityTitle: "Communauté Honeymoon",
    ourCreatorsTitle: "Nos créatrices",
    bnav2257: "Mention 2257",
    bnavCgu: "CGU",
    bnavPrivacy: "Confidentialité",
    bnavPricing: "Prix",
  },
  en: {
    gateSub: 'Private access',
    gateEnter: 'Enter',
    gateNoteB: 'Technical note:',
    gateNote: 'this access code is a simple browser-side barrier, not real authentication.',
    gateErr: 'Incorrect code.',
    gatePassPh: "Access code",
    creatorPassPh: "Password",
    creatorEmailPh: "Email",
    creatorEmailLabel: "Login email (creator)",
    creatorEmailNote: "The creator creates her own account (\"Create my creator account\" link on the login screen) — paste here the email she chose to activate her profile. Works for an unlimited number of creators, without ever touching the code.",
    creatorSignupLink: "No account yet? Create my creator account",
    creatorSignupSub: "Create my creator account",
    creatorSignupNote: "Create your own account. Your profile will be activated by the Honeymoon team once your application is approved.",
    creatorSuSubmit: "Create my account",
    creatorLoginLink: "← Back to login",
    creatorSignupSuccessToast: "Account created! The team will now activate your profile.",
    creatorNotActivatedErr: "Account found, but no profile is linked to it yet. Contact the Honeymoon team.",
    noPhotoYet: "No photo yet",
    tipMenuContentRequired: "Add content (photo, video or audio) before saving this line.",
    mockPurchaseNotice: "🔧 Mock purchase — the real payment system is coming soon. No amount was charged.",
    visitorNeedsAccountPurchase: "Sign up for free to purchase content — an account is required to store it in your personal gallery.",
    memberLoggedInToast: "Logged in!",
    memberBioEditBtn: "Edit",
    memberBioCancelBtn: "Cancel",
    memberBioDeleteBtn: "Delete",
    memberBioEmpty: "No biography yet. Click edit to write one.",
    myFamilyComments: "Comments",
    tipMenuEarnNote: "You'll receive about {amount}€ (60%) from this price.",
    tipMenuContentLabel: "Content to sell",
    tipMenuContentNote: "Import or capture directly the photo/video/audio you'll sell for this theme.",
    tipMenuOrderBtn: "Order",
    tipMenuOrderPrefill: "Hi, I'd like to order: {theme} ({price}€)",
    tipOrderCardLabel: "Tip Menu order",
    tipOrderDeliverBtn: "Deliver / Paid",
    ordersCustomTabLabel: "Custom orders",
    ordersTipTabLabel: "Tip Menu orders",
    ordersCustomTabNote: "All custom requests you've received, with the member's name and their request. Deliver the content or open a discussion to nail down the details.",
    ordersTipTabNote: "All orders placed from your Tip Menu, with the member's name. The content already exists: click Deliver / Paid to unlock it, or discuss delivery timing.",
    ordersCustomEmpty: "No pending custom orders.",
    ordersTipEmpty: "No pending Tip Menu orders.",
    ordersDiscussBtn: "💬 Discuss",
    tipMenuCurrencyCompareLink: "Compare with my currency (Google)",
    chatModBtnLabel: "Tips & rules",
    chatModTip1: "Be respectful and kind: a good conversation always starts with politeness.",
    chatModTip2: "Feel free to ask open questions so the conversation stays smooth and enjoyable for both of you.",
    customOrderTypeChooseLabel: "Choose a content type",
    customOrderTypeChooseNote: "There are 3 possible choices: photo, video or audio. Pick the one matching what you'll deliver.",
    customOrderHelp1: "This order is a custom request: describe exactly what you want (length, outfit, mood).",
    customOrderHelp2: "Stay respectful in your request — no nudity, no explicit or illegal content.",
    customOrderHelp3: "The price isn't negotiated directly with you: the creator sets the price (within platform limits) at delivery time.",
    customOrderHelp4: "Once delivered, your order appears in 'My purchases' — you can view it anytime.",
    tipMenuHowTitle: "How does this work?",
    tipMenuHowP1: "The Tip Menu is your ready-made content menu: set a theme, a price (within the platform's limit), and directly import the photo, video or audio you're selling.",
    tipMenuHowP2: "There's no negotiation on these items: the price is already fixed alongside the description. The member just clicks 'Order' to place the order.",
    tipMenuHowP3: "A member can also request a fully custom order directly from chat (cart button) — you deliver the content and set the price at that time.",
    tipMenuHowMemberP1: "The Tip Menu shows the ready-made content the creator offers, with prices.",
    tipMenuHowMemberP2: "No negotiation: the price is already fixed alongside the description. Click 'Order' to place your order directly.",
    tipMenuHowMemberP3: "You can also ask for something fully custom via the cart button in chat — she'll deliver the content and set the price.",
    customOrderBtnLabel: "Custom order",
    customOrderFormNote: "Describe precisely the kind of video, photo or audio you want.",
    customOrderFormPh: "E.g.: a 30-second video in red lingerie, soft mood...",
    customOrderSendBtn: "Send request",
    customOrderSentToast: "Your request was sent!",
    customOrderDeliverTitle: "Deliver this order",
    customOrderDeliverBtn: "Deliver to client",
    customOrderDeliveredToast: "Content delivered!",
    customOrderDeliveredNote: "Order delivered",
    customOrderPendingNote: "Awaiting delivery",
    customOrderViewBtn: "View my order",
    customOrderUnauthorized: "Unauthorized link: only the relevant creator can deliver this order.",
    customOrderSavedToPurchases: "Added to your purchases!",
    customOrderPurchasesTitle: "Custom orders",
    customOrderPurchasesNone: "No custom orders yet.",
    chatBotBtnLabel: "Auto message & banner",
    chatBotWelcomeLabel: "Automatic welcome message",
    chatBotWelcomeNote: "Sent automatically when the chat opens, up to 4 times per person. Add emoji to make it warmer.",
    chatBotWelcomePh: "E.g.: Hey, so glad you're here 💕 Tell me what would make you happy...",
    chatBotBannerLabel: "Scrolling banner",
    chatBotBannerNote: "A series of messages that cycle at the top of the chat, visible to the person you're talking with.",
    chatBotBannerAddBtn: "Add a message",
    chatBotIntervalLabel: "Interval (seconds)",
    levelDesc_diamond: "A remarkable level of support toward the creators.",
    bioCoverLabel: "Profile presentation photo/video",
    bioCoverNote: "This concerns your profile presentation page (different from your card's cover photo/video).",
    bioNarrativeMainTitle: "Creator's Profile",
    coverBelongsToShowcaseNote: "This concerns your public showcase page (different from your profile sheet).",
    coverPhotoTip: "A beautiful, well-lit, sensual and attractive photo to attract interest and followers.",
    mediaCommentsTitle: "Comments on this content",
    bioNarrativePersonalityTitle: "Her personality",
    bioNarrativePassionsTitle: "Her passions",
    bioNarrativeContentTitle: "What she offers",
    bioNarrativeUniverseTitle: "Her world",
    bioNarrativeLookingForTitle: "What she's looking for",
    bioNarrativeAmbitionsTitle: "Her ambitions",
    bioNarrativeAudienceTitle: "Where to find her",
    reportPrefillMediaComment: "Comment on a photo/video",
    commentReplyBtn: "Reply",
    vitrineEnterBtn: "Enter",
    agencyLogout: "Log out",
    visitorNeedsAccountFavorite: "Sign up for free to add creators to your favorites — coming soon.",
    visitorNeedsAccountChat: "Sign up for free to message this creator — coming soon.",
    commentModeAnonymous: "Anonymous",
    commentModeVisitor: "I'm a visitor",
    commentModeMember: "Use my username",
    commentModeCustom: "Enter a nickname",
    commentNamePh: "Your name or nickname",
    commentNameRequired: "Please enter your name or nickname before posting.",
    paidGalleryTitle: "Paid gallery",
    paidGalleryNote: "Sell exclusive photos and videos directly from your space. Allowed content: lingerie, sexy outfits, sensual dance. No nudity.",
    paidSalesLabel: "sales",
    paidTotalRevenue: "Total revenue",
    paidTotalSales: "Total sales",
    paidAddPhoto: "+ Paid photo",
    paidAddVideo: "+ Paid video",
    paidNoItems: "No paid content yet.",
    paidOrdersTitle: "Unlock requests",
    paidOrdersLoading: "Loading…",
    paidDescLabel: "Description",
    paidDescPh: "Describe this content to make it enticing…",
    paidPriceLabel: "Price (€)",
    paidTeaserLabel: "Teaser (5 seconds, free to view)",
    paidFullVideoLabel: "Full video (locked)",
    paidPhotoLabel: "Photo (locked)",
    paidFileRequired: "Please add a file before saving.",
    paidTeaserRequired: "A teaser is required for a paid video.",
    paidNoOrders: "No pending requests.",
    paidMarkPaid: "Mark as paid",
    paidMarkedPaidToast: "Sale confirmed!",
    paidExclusiveTitle: "Exclusive content",
    paidExclusiveNote: "Free preview below, unlock the full content.",
    exclusiveSalesCount: "already unlocked {count} times",
    paidTeaserBadge: "Free teaser",
    paidUnlockBtn: "Unlock for",
    paidLockedPhoto: "Locked exclusive photo",
    paidUnlockExplain: "Send your request: you'll receive payment instructions, and the content will be sent once payment is confirmed.",
    paidContactLabel: "Contact (email, phone or WhatsApp)",
    paidContactPh: "e.g. email or WhatsApp number",
    paidContactRequired: "Please enter your name and a way to contact you.",
    paidSendRequest: "Send request",
    paidRequestSent: "Request sent! You'll be contacted for payment.",
    paidPendingAgency: "Pending agency validation",
    paidSplitLabel: "Split:",
    paidSplitCreator: "creator share",
    paidInvoiceAndValidate: "Invoice & confirm",
    paidPaymentInstructionsIntro: "Your request has been recorded. Make the transfer below with the reference, and you'll receive the content once payment is confirmed.",
    paidRefLabel: "Reference",
    paidAmountLabel: "Amount",
    paidHolderLabel: "Account holder",
    paidSalesPanelBtn: "Sales",
    paidSalesPanelTitle: "Pending sales",
    paidVideoPrompt: "Click to choose a video",
    paidThisMonthLabel: "This month",
    paidAllTimeLabel: "All-time total",
    toolsTitle: "Tools",
    toolsNote: "Your personal space: calendar, notes, calculator, income/expense tracking and practical tips. This data stays on your phone, it isn't shared.",
    toolCalendar: "Calendar",
    toolNotes: "Notes",
    toolCalc: "Calculator",
    toolFinance: "Finance",
    toolAdvice: "Tips",
    toolBanner: "Banner",
    toolBannerNote: "Schedule a banner (date, time, duration) that will show on your public page inviting your followers to send you a gift — birthday, Valentine's, Christmas, New Year, or your own custom message.",
    bannerActiveLabel: "Active banner",
    bannerActiveUntil: "Until",
    bannerRemoveBtn: "Remove banner",
    bannerRemoveConfirm: "Remove the current banner?",
    bannerTemplateLabel_birthday: "Birthday",
    bannerTemplateLabel_valentine: "Valentine's",
    bannerTemplateLabel_christmas: "Christmas",
    bannerTemplateLabel_newyear: "New Year",
    bannerTemplateLabel_custom: "Custom",
    bannerTemplate_birthday: "🎂 My birthday is coming up! If you're feeling generous, a little gift would make my day 💛",
    bannerTemplate_valentine: "💘 Happy Valentine's Day! Send me a little gift to show me some love 😘",
    bannerTemplate_christmas: "🎄 Merry Christmas! A little gift under the tree for me would make my heart skip a beat 🎁",
    bannerTemplate_newyear: "🎆 Happy New Year! Start the year off right with a little gift for me ✨",
    bannerTemplate_custom: "",
    bannerMessageLabel: "Your message",
    bannerMessagePh: "Write whatever you want — with your name or not, up to you…",
    bannerDateLabel: "Launch date",
    bannerTimeLabel: "Time",
    bannerDurationLabel: "Display duration",
    bannerDuration1Day: "1 day",
    bannerDuration3Days: "3 days",
    bannerDuration7Days: "7 days",
    bannerDuration14Days: "14 days",
    bannerPublishBtn: "Launch the banner",
    bannerMessageRequired: "Write your message first.",
    bannerDateRequired: "Pick a valid date and time.",
    bannerPublishedToast: "Banner scheduled!",
    bannerViewerCta: "Send a gift",
    tierNudgeMessage: "Think about posting an exclusive video to thank your followers for helping you reach this milestone 💛",
    tierNudgeDismissBtn: "Got it",
    toolIdeas: "Honeymoon Ideas",
    ideasIntroTitle: "Welcome to your pro space",
    ideasIntroBody: "By joining Honeymoon, you're launching your own business: you're an independent, self-employed adult content creator. This is your business — it's up to you to run it seriously and professionally with your followers, so they keep coming back and supporting you. These ideas come from Honeymoon's leadership and team, to help you get the most out of it.",
    ideasWelcomeTitle: "Automatic welcome message",
    ideasWelcomeNote: "As soon as a member starts following you, this message is sent to them automatically and for free in chat — a great first impression, with no effort on your part.",
    ideasWelcomePh: "E.g.: Thanks for following me 💛 Feel free to message me, I reply to everyone!",
    ideasWelcomeSaveBtn: "Save message",
    ideasWelcomeSavedToast: "Welcome message saved!",
    ideasTierTitle: "Popularity milestones",
    ideasTierBody: "Every time you reach a new tier (bronze, silver, gold…), you'll get a small reminder in your Popularity tab suggesting you post exclusive content to thank your followers for helping you get there.",
    ideasTipsTitle: "Tips to keep your community engaged",
    ideasTipsNote: "These are suggestions, not obligations — take what fits you.",
    ideasTip1: "Reply to your messages regularly: responsiveness builds loyalty more than content volume.",
    ideasTip2: "Keep a steady posting rhythm rather than long silences followed by bursts.",
    ideasTip3: "Save something special (a photo, video, or voice note) for your most loyal followers.",
    ideasTip4: "Stay yourself: a recognizable personality builds loyalty better than generic content.",
    ideasTip5: "Set your boundaries clearly from the start — it avoids misunderstandings and builds respect.",
    audioClearBtn: "Remove audio",
    ideasWelcomeAudioLabel: "Voice message (optional)",
    bannerAudioLabel: "Voice message (optional)",
    bannerColorBgLabel: "Background color",
    bannerColorTextLabel: "Text color",
    bannerScrollLabel: "Scrolling",
    bannerBlinkLabel: "Blinking",
    bannerScrollDurationLabel: "Scroll duration (seconds)",
    toolCalendarPh: "Add a note for this day…",
    toolNotesPh: "Write anything here…",
    toolCalcError: "Error",
    toolIncome: "Income",
    toolExpense: "Expenses",
    toolBalance: "Balance",
    toolFinLabelPh: "Name (e.g. Lighting purchase)",
    toolAddEntry: "Add",
    toolNoEntries: "No entries yet.",
    toolPaymentAccessNote: "These buttons open the official PayPal and M-Pesa websites in your browser — the site cannot access your accounts directly.",
    toolFinMissing: "Please fill in a name and a valid amount.",
    toolEstimateEarnings: "Estimate my earnings",
    toolEstimatorIntro: "Tell me how much you sell each item for and how many you expect to sell per month, and I'll calculate an estimate.",
    toolEstimatorPrice: "Average price per item (€)",
    toolEstimatorVolume: "Estimated sales per month",
    toolEstimatorCalc: "Calculate my estimate",
    toolEstimatorResult: "With an average price and {monthly}€ estimated revenue this month, your share (at {percent}%) would be about {share}€. This is a simple estimate — the real amount depends on demand, content quality and consistency.",
    toolCalcReasonPh: "Reason for calculation (e.g. monthly budget)",
    toolCalcHistory: "Calculation history",
    toolCalcNoReason: "Untitled",
    toolCalcNoResult: "Do a calculation first before saving.",
    toolChatLang: "Chat language",
    toolAskAnything: "Ask your question in your own words…",
    toolNoMatch: "I don't have a ready answer for that — try rephrasing, or pick a topic from the list above.",
    paidAddAudio: "+ Audio message",
    paidAudioLabel: "Audio message (locked)",
    paidAudioPrompt: "Click to choose an audio file",
    paidAudioDescPh: "Message topic (e.g. a sweet word, a dare, a confidence…)",
    toolDailyBudgetTitle: "Daily budget",
    toolDailyBudgetNote: "How much you can spend per day without risking an overdraft, based on your current balance.",
    toolDailyBudgetDays: "Days remaining",
    toolDailyBudgetCalc: "Calculate",
    toolDailyBudgetResult: "You can spend about {amount}€ per day for {days} days without going negative.",
    toolDailyBudgetNegative: "Your balance is already negative or zero — avoid spending for now.",
    toolTaxNotice: "Important: depending on your country, income earned here may be subject to tax and mandatory declarations (self-employment, small-business status, etc.). Check with your country's tax authority to know your exact obligations and avoid surprises about what you actually keep. If no tax rule applies to your situation, this message does not concern you.",
    toolCurrency: "Currency",
    toolCompareCurrencies: "Compare currencies",
    toolCurrencyLoading: "Loading rates…",
    toolCurrencyComparedTo: "Rates against",
    toolCurrencyDate: "Rate as of",
    toolCurrencyError: "Could not load rates (check your internet connection).",
    paidAudioImport: "Import a file",
    paidAudioRecordNow: "Record now",
    paidAudioRecordPrompt: "Tap to start recording",
    paidAudioRecording: "Recording… tap to stop",
    paidAudioRecordDone: "Recording done — listen below",
    paidAudioMicError: "Couldn't access the microphone. Check your browser permissions.",
    captureNowBtn: "Take now",
    importFileBtn: "Import a file",
    filesSelected: "files selected",
    paidSeeInMyCurrency: "See in my currency",
    paidSplitBreakdown: "Payment breakdown",
    paidSplitPlatform: "Honeymoon share",
    legalLink2257: "2257 Statement",
    legalLinkTerms: "Terms",
    legalLinkPrivacy: "Privacy",
    legalLinkPricing: "Pricing & Refunds",
    legalDocTitle2257: "2257 Compliance Statement",
    legalDocTitleTerms: "Terms and Conditions",
    legalDocTitlePrivacy: "Privacy Policy",
    legalDocTitlePricing: "Pricing and Refund Policy",
    burgerHome: "Home",
    burgerTagline: "An exclusive world of creators",
    burgerSectionInfo: "Information",
    burgerSectionAccount: "Account",
    burgerBecomeMember: "Become a member",
    burgerApplyModel: "Apply to become a creator",
    burgerFaq: "FAQ",
    burgerCreatorLogin: "Creator space login",
    burgerAgencyLogin: "Private access for agencies",
    burgerRules: "Site rules",
    legalDocTitleRules: "Site Rules",
    soonBecomeMemberTitle: "Become a member — coming soon",
    soonBecomeMemberBody: "This feature is coming soon. Check back soon to find out how to join the Honeymoon community as a member.",
    memberFreeBadge: "100% free account — no sign-up fees",
    memberLoginTitle: "Log in",
    memberSignupTitle: "Create a member account",
    memberSignupLine: "Chat with your favorite creators and unlock their Tip Menu. Free account — you only pay for what you choose to buy.",
    memberHomeWelcomeLine: "Follow your favorite creators, chat with them, and find all your purchases here.",
    memberDiscoverCreatorsBtn: "Discover creators",
    memberIdentifierLabel: "Username or email",
    memberIdentifierPh: "your_username or you@email.com",
    memberUsernameLabel: "Username",
    memberUsernamePh: "Pick a username",
    memberEmailLabel: "Email",
    memberEmailPh: "you@email.com",
    memberPasswordLabel: "Password",
    memberPasswordPh: "Pick a password (6 characters min.)",
    memberPasswordLoginPh: "Your password",
    memberConfirmPasswordLabel: "Confirm password",
    memberConfirmPasswordPh: "Retype your password",
    memberLoginBtn: "Log in",
    memberSignupBtn: "Create my account",
    memberNoAccount: "No account yet?",
    memberCreateOne: "Create one",
    memberHaveAccount: "Already a member?",
    memberLoginInstead: "Log in",
    memberForgotLink: "Forgot password or username?",
    memberBackToLogin: "← Back to login",
    memberErrFillAll: "Please fill in all fields.",
    memberErrPassMismatch: "Passwords don't match.",
    memberErrPassShort: "Password must be at least 6 characters.",
    memberErrUsernameTaken: "This username is already taken.",
    memberErrUsernameFormat: "Username must be 3-20 characters (letters, numbers, dots, dashes, underscores).",
    memberErrEmailInUse: "An account already exists with this email.",
    memberErrInvalidEmail: "Invalid email address.",
    memberErrWeakPass: "This password is too weak.",
    memberErrLoginFailed: "Incorrect username/email or password.",
    memberErrUnknown: "Something went wrong. Try again.",
    memberErrNoConnection: "Server connection unavailable — reload the page and try again.",
    memberVerifyTitle: "Confirm your account",
    memberVerifyBody: "A confirmation email was just sent to {email}. Open it and click the link to activate your member account. Check your spam folder if you don't see it.",
    memberVerifyCheckBtn: "I've confirmed, continue",
    memberVerifyResendBtn: "Resend confirmation email",
    memberVerifyResendToast: "Confirmation email resent.",
    memberVerifyStillPending: "Your account isn't confirmed yet. Check your inbox (and spam folder), then click the link before continuing.",
    memberVerifyLogout: "Log out",
    memberHomeWelcome: "Welcome, {username}!",
    memberHomeConfirmed: "Your member account is active and confirmed.",
    memberHomeSoon: "The member area (content, subscriptions...) is coming very soon. Check back!",
    memberHomeLogout: "Log out",
    memberLoggedOutToast: "You're logged out.",
    memberSignupSuccessToast: "Account created successfully.",
    memberForgotTitle: "Forgot password or username",
    memberForgotBody: "Enter the email linked to your account. If an account exists, you'll receive a link to reset your password (your username will be shown once you're logged in).",
    memberForgotEmailPh: "you@email.com",
    memberForgotSendBtn: "Send the link",
    memberForgotSentTitle: "Email sent",
    memberForgotSentBody: "If an account exists with this email, a reset link was just sent. Open it to choose a new password.",
    memberTabProfile: "Profile",
    memberTabPurchases: "My purchases",
    memberUnverifiedBanner: "Account not confirmed yet — email sent to {email}.",
    memberResendShort: "Resend",
    memberResentShort: "Resent ✓",
    memberAvatarChange: "Change photo",
    memberLocationLabel: "Location",
    memberLocationPh: "City, country...",
    memberBioLabel: "Biography",
    memberBioPh: "Tell us about yourself...",
    caThisMonthShort: "This month's earnings",
    coverVideoBtn: "Mini video",
    coverVideoNote: "You can use a photo, or a short intro video — it often attracts more views and followers.",
    coverVideoRules: "60 seconds maximum. No nudity — lingerie or sexy outfits only, same as your photos. No explicit sexual gestures (e.g. simulated fingering) — twerk, dance and sensual poses remain allowed. Sensual is welcome, but never the simulation of a sexual act.",
    coverVideoTooLong: "This video is longer than 60 seconds — please choose a shorter one.",
    levelDescPrefix: "Level",
    levelDesc_gray: "The starting point for every creator.",
    levelDesc_bronze: "A first community is starting to form around you.",
    levelDesc_silver: "Your popularity is growing, more and more members are following you.",
    levelDesc_gold: "You're among the well-established creators on Honeymoon.",
    levelDesc_purple: "A strong community actively supports you.",
    levelDesc_red: "The maximum level — you're among the most popular creators on the site.",
    publicIntroLabel: "Describe yourself for the public",
    publicIntroNote: "10 lines maximum. This text will appear on your public page, below your followers.",
    publicIntroPh: "E.g.: I'm passionate about dance and love sharing playful moments with you...",
    myFamilyPopularity: "Popularity",
    popularityTabNote: "Your popularity badge, your followers, and who you follow.",
    followingLabel: "Following",
    followersLabel: "Followers",
    likesLabel: "Likes",
    followersListTitle: "Followers",
    followingListTitle: "Following",
    tierLabel_gray: "Starter",
    tierLabel_bronze: "Bronze",
    tierLabel_silver: "Silver",
    tierLabel_gold: "Gold",
    tierLabel_red: "Top creator",
    tierLabel_purple: "Purple",
    tierLabel_diamond: "Diamond",
    uxdLabel: "UXD",
    uxdExplainNote: "UXD, your standing on Honeymoon. Every bit of support moves you up toward a rank recognized across the whole community — all the way to the top tier.",
    uxdLevelDesc_gray: "The starting point for every new member.",
    uxdLevelDesc_silver: "You're starting to stand out among fans.",
    uxdLevelDesc_bronze: "Your status is climbing — you're entering the circle of recognized members.",
    uxdLevelDesc_gold: "You're among the most visible members of the community.",
    uxdLevelDesc_purple: "An elite rank, reserved for a handful of members.",
    uxdLevelDesc_red: "The top rank — your status sits at the summit of Honeymoon.",
    tipMenuTabLabel: "Tip Menu",
    tipMenuTabNote: "Fill in your menu by theme (photo, video, audio). Prices are set by the platform — pick them from the list. Publish so it appears on your page.",
    tipMenuThemePh: "Theme name (e.g. lingerie)",
    tipMenuColTheme: "Theme",
    tipMenuColPhoto: "Photo",
    tipMenuColVideo: "Video",
    tipMenuColAudio: "Audio",
    tipMenuNoPrice: "—",
    tipMenuAddRow: "Add a theme",
    tipMenuRulesLabel: "Explain the rules for each theme",
    tipMenuRulesPh: "E.g.: Lingerie = photo in fine lingerie, no nudity. Sensual dance = 30-60s video...",
    tipMenuPriceLockedNote: "Prices are set by Honeymoon — you can only choose among the offered amounts.",
    tipMenuPublishBtn: "Publish to my page",
    tipMenuPublishedToast: "Tip Menu published to your page!",
    tipMenuCustomNote: "Something specific in mind? Custom requests can be discussed directly in chat.",
    tipMenuRowExplain: "For each line: choose the content type (photo, video, or audio), give it a theme, a price, and a description of what's included.",
    tipMenuPriceLabel: "Price",
    tipMenuDescLabel: "Description (what's included)",
    tipMenuDescPh: "E.g.: 30-second video, black lingerie outfit, no nudity.",
    tipMenuEditRow: "Edit",
    tipMenuRowDoneBtn: "Save this line",
    tipMenuThemeRequired: "Add a theme name before saving.",
    tipMenuHelpTheme: "The name of what you're offering, e.g. \"Red lingerie\" or \"Sensual dance\".",
    tipMenuHelpPrice: "Pick a price between {min}€ and {max}€ for this content type. If you go above the allowed maximum, it will automatically be capped at {max}€.",
    tipMenuHelpDesc: "Describe in a few words what's included (duration, outfit, what's shown or not). 20 words max.",
    tipMenuPriceClamped: "Price capped at the allowed maximum: {max}€.",
    tipMenuHelpEmoji: "You can add one or several emojis, or leave it empty — the default emoji can be erased.",
    tipMenuMaxRows: "Maximum 25 lines in your Tip Menu.",
    tipMenuTheme_lingerie: "Lingerie",
    tipMenuTheme_danse_sensuelle: "Sensual dance",
    tipMenuTheme_strip_tease: "Striptease",
    tipMenuTheme_pov_intime: "Intimate POV",
    tipMenuTheme_roleplay: "Roleplay",
    tipMenuTheme_fetish_pieds: "Foot fetish",
    tipMenuTheme_costume_theme: "Themed costume",
    tipMenuTheme_exterieur: "Outdoor",
    tipMenuTheme_duo_couple: "Duo / couple",
    tipMenuTheme_demande_personnalisee: "Custom request",
    followBtn: "Follow",
    followingBtn: "Following",
    membersViewerBtn: "Members",
    membersViewerTitle: "Members sharing their profile",
    membersViewerEmpty: "No members are sharing their bio or photos yet.",
    myMembersTabNote: "Find members who chose to share their bio or photos with you, the ones you follow, and your favorites.",
    myMembersFilterAll: "All",
    myMembersFilterFavorites: "Favorites",
    myMembersNoFavorites: "No favorites yet.",
    myMembersFavoriteBtn: "Favorite",
    myMembersUnfavoriteBtn: "Remove",
    memberVisibilityLabel: "Who can see",
    memberVisibilityEveryone: "All creators",
    memberVisibilityFavorites: "Only my favorites",
    memberVisibilityNobody: "Nobody",
    memberBioVisibleLabel: "Make my bio visible to the creator",
    memberSubtabInfos: "My info",
    memberSubtabPhotos: "My photos",
    memberSubtabPassword: "Password",
    memberPrivateFieldNote: "Never visible to anyone but you.",
    memberBioVisibilityExplain: "Based on your choice above, your bio may be seen by the relevant creators. The rest of your profile (email, purchases, password) is never visible.",
    memberPhotosVisibilityExplain: "Based on your choice above, these photos may be seen by the relevant creators. They stay separate from your purchases.",
    memberBioHiddenNote: "Your bio is only visible to you. The rest of your profile (email, purchases, password...) is never visible to creators or other members.",
    memberSaveBtn: "Save",
    memberSavedToast: "Changes saved.",
    memberChangePasswordTitle: "Change password",
    memberCurrentPasswordLabel: "Current password",
    memberCurrentPasswordPh: "Your current password",
    memberNewPasswordLabel: "New password",
    memberNewPasswordPh: "New password (6 characters min.)",
    memberChangePasswordBtn: "Update password",
    memberPasswordChangedToast: "Password updated.",
    memberErrWrongCurrentPass: "Current password is incorrect.",
    memberPurchaseHistoryTitle: "Payment history",
    memberPurchaseNone: "No purchases yet.",
    memberPurchasePending: "pending",
    memberPurchasePaid: "paid",
    memberPurchasePhotosTitle: "Purchased photos",
    memberPurchaseVideosTitle: "Purchased videos",
    memberPurchaseNoPhotos: "No photos purchased yet.",
    memberPurchaseNoVideos: "No videos purchased yet.",
    memberPurchaseLoadErr: "Couldn't load your purchases right now. Try again later.",
    applyTitle: "Apply to become a model",
    applyIntro: "This form is open to everyone. Fill it in and it will be sent directly to the Honeymoon team — no fees, no obligation.",
    applyBusinessPitch: "Joining Honeymoon means launching your own business: you run it as an independent, self-employed content creator, at your own pace and on your own terms.",
    applyNameLabel: "Name / desired username",
    applyNamePh: "Your first name or the username you'd like to use",
    applyContactEmailLabel: "Contact email",
    applyContactEmailPh: "you@email.com",
    applyContactPhoneLabel: "Phone / other contact (optional)",
    applyContactPhonePh: "WhatsApp, Telegram, phone number...",
    applyCountryLabel: "Country / location",
    applyCountryPh: "City, country",
    applyWorkingElsewhereLabel: "Are you already working on another site or with another agency?",
    applyWorkingElsewhereNo: "No, none",
    applyWorkingElsewhereYes: "Yes",
    applyWorkingElsewhereDetailLabel: "Site / agency name + your ID or username there",
    applyWorkingElsewhereDetailPh: "E.g. SiteName — username123",
    applyMotivationLabel: "Why do you want to join Honeymoon?",
    applyMotivationPh: "Your motivation, what you're looking for, your availability...",
    applySocialLabel: "Social media / portfolio (optional)",
    applySocialPh: "Instagram, TikTok, link to your photos...",
    applyLegalTitle: "Site conditions",
    applyLegalText: "Honeymoon works with a collaboration agreement (non-exclusive unless otherwise agreed): allowed content is limited to lingerie / sexy outfits / sensual dance — no nude content is accepted on this platform. For any paid content sold, the split is 60% for the creator and 40% for Honeymoon for platform management. Identity and age verification (18 years minimum) is mandatory before any publishing. The full agreement is presented and signed electronically if your application is accepted.",
    applyCheck18: "I confirm I am 18 years old or older.",
    applyCheckConditions: "I have read and accept the conditions above (allowed content, 60/40 split, identity verification).",
    applyCheckData: "I agree that my information will be shared with the Honeymoon team as part of reviewing my application.",
    applySendBtn: "Send my application",
    applyErrFillRequired: "Please fill in all required fields.",
    applyErrChecks: "Please check all 3 boxes to send your application.",
    applySentTitle: "Application sent!",
    applySentBody: "Thank you! Your application has been sent to the Honeymoon team. You'll be contacted directly at the email or contact you provided if your profile is selected.",
    applySentClose: "Close",
    applicationsPanelBtn: "Applications",
    applicationsNoneYet: "No applications yet.",
    memberTabFavorites: "Favorites",
    memberUseMyLocation: "Use my location",
    memberGeolocLoading: "Locating…",
    memberGeolocDenied: "Location denied or unavailable.",
    memberGeolocUnsupported: "Geolocation isn't available on this device.",
    memberMyPhotosTitle: "My photos",
    memberMyPhotosNote: "Personal photos, separate from your purchases. Choose below whether creators can see them.",
    memberPhotoDeleteBtn: "Delete this photo",
    memberPhotoDeleteConfirm: "Permanently delete this photo?",
    memberPhotosVisibleLabel: "Make my photos visible to creators",
    memberFavoritesNone: "No favorite creators yet. Tap ♡ on a profile to add one.",
    memberFavoritesHype: "✨ Your favorites, all in one place — never miss what's new from them.",
    memberMessagesHype: "💬 One message, one connection. They love hearing from you.",
    memberFavoriteToggle: "Add/remove from favorites",
    memberFavoriteAdded: "Added to your favorites.",
    memberFavoriteRemoved: "Removed from your favorites.",
    myCommentsTitle: "Comments received",
    myCommentsNote: "Comments left on your profile by visitors. You can delete a comment you find inappropriate or offensive.",
    myCommentsNone: "No comments yet.",
    myCommentsDelete: "Delete this comment",
    myCommentsConfirmDelete: "Permanently delete this comment?",
    myCommentsReportToTeam: "Report to team",
    logoutConfirm: "Log out of your member account?",
    deletionsPanelBtn: "Deletions",
    deletionsNoneYet: "No deletion requests yet.",
    deletionStatusCancelled: "cancelled",
    deletionStatusCompleted: "deleted",
    deletionEligibleNow: "delay elapsed — ready",
    deletionDaysLeft: "{n} day(s) left",
    deletionConfirmBtn: "Delete permanently",
    deletionFinalConfirm: "PERMANENTLY delete {name}'s account and all their content? This cannot be undone.",
    deletionCompletedToast: "Account permanently deleted.",
    creatorRulesArticleTitle: "Rules, rights and duties",
    creatorRulesArticleBody: "As a creator on Honeymoon, you keep 60% of your paid content sales (40% for platform management). Allowed content is limited to lingerie, sexy outfits and sensual dance — no nude content is accepted. A valid ID is required before any publishing. You remain free to manage your content, and you can request your account's deletion at any time below.\n\nAccount deletion: once your request is sent with a delay (1 to 7 days) and your reason, the Honeymoon team is notified. You can cancel your request at any time before the delay elapses. Once it does, deletion becomes possible and your profile, photos, videos and comments are permanently erased.",
    deletionPendingBanner: "Your account deletion is scheduled in {n} day(s).",
    deletionCancelBtn: "Cancel request",
    deletionCancelledToast: "Deletion request cancelled.",
    deletionOpenBtn: "Delete my creator account",
    deletionDelayLabel: "Delay before deletion",
    deletionDelayOption: "{n} day(s)",
    deletionReasonLabel: "Reason for deletion",
    deletionReasonPh: "Explain why you want to delete your account...",
    deletionSubmitBtn: "Send request",
    deletionRequestedToast: "Deletion request sent.",
    memberDeleteAccountTitle: "Delete my account",
    memberDeleteAccountNote: "This permanently deletes your member account, profile and personal photos. A confirmation email will be sent to you.",
    memberDeleteAccountBtn: "Delete my account",
    memberDeleteAccountConfirm1: "Are you sure you want to delete your member account? This cannot be undone.",
    memberDeleteAccountConfirm2: "Final confirmation: your profile, bio and personal photos will be permanently deleted. Continue?",
    memberDeleteAccountDone: "Your account has been deleted. A confirmation email was sent to you.",
    memberDeleteRequiresRecent
